// Generated by scripts/generate-configs.ts — edit languages/node/eslint.config.base.ts instead.

import js from "@eslint/js";
import globals from "globals";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node } as Record<string, boolean>,
    },
  },
  eslintConfigPrettier,
];
