// Generated by scripts/generate-configs.ts — edit shared/playwright/specs/ instead.
/**
 * トップページの E2E サンプル。
 * 見本として残し、プロジェクトに合わせて編集・追加してください。
 */

import { expect, test } from '@playwright/test';

test.describe('トップページ', () => {
  test('タイトルと見出しが表示される', async ({ page }) => {
    await page.goto('/');
    await expect(page).toHaveTitle(/Next.js/);
    await expect(page.getByRole('heading', { level: 1 })).toContainText(
      'Next.js Starter Template',
    );
  });
});
