/**
 * Generates GitHub Actions workflows and dependabot.yml for templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { ROOT } from "../lib/utils.js";
import {
  TEMPLATE_DIRS,
  FULL_TEMPLATE_DIRS,
  CODE_CHECK_SOURCE,
  FULL_CODE_CHECK_SOURCE,
  TEST_SOURCE,
  FULL_TEST_SOURCE,
  FULL_CI_SOURCE,
  NODE_VERSION_DIRS,
  RUBY_VERSION_DIRS,
} from "../lib/stacks.js";

export function run(): void {
  const WORKFLOWS_DIR = join(ROOT, "shared", "ci", "workflows");
  const GEN_HEADER = "# Generated by scripts/commands/generate-configs.ts — edit shared/ci/workflows/<name> instead.\n";

  // ── static-analysis.yml ────────────────────────────────────────────────────

  const STATIC_ANALYSIS_SRC = join(WORKFLOWS_DIR, "static-analysis.yml");
  const STATIC_ANALYSIS_HEADER = "# Generated by scripts/commands/generate-configs.ts — edit shared/ci/workflows/static-analysis.yml instead.\n";
  const staticAnalysisContent = STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, "utf8");

  for (const dir of [...TEMPLATE_DIRS, ...FULL_TEMPLATE_DIRS]) {
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "static-analysis.yml");
    writeFileSync(outPath, staticAnalysisContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── code-check.yml ─────────────────────────────────────────────────────────

  for (const [dir, srcName] of Object.entries({ ...CODE_CHECK_SOURCE, ...FULL_CODE_CHECK_SOURCE })) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "code-check.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── test.yml ───────────────────────────────────────────────────────────────

  for (const [dir, srcName] of Object.entries({ ...TEST_SOURCE, ...FULL_TEST_SOURCE })) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "test.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── ci.yml ─────────────────────────────────────────────────────────────────

  for (const [dir, srcName] of Object.entries(FULL_CI_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "ci.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── ci-e2e-nextjs.yml / ci-lighthouse-nextjs.yml (reusable, full-templates with CI only) ──

  const CI_REUSABLE_WORKFLOWS = ["ci-e2e-nextjs.yml", "ci-lighthouse-nextjs.yml"];
  for (const dir of Object.keys(FULL_CI_SOURCE)) {
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    for (const srcName of CI_REUSABLE_WORKFLOWS) {
      const content =
        GEN_HEADER.replace("<name>", srcName) +
        readFileSync(join(WORKFLOWS_DIR, srcName), "utf8");
      writeFileSync(join(outDir, srcName), content, "utf8");
      console.log("Generated:", join(outDir, srcName));
    }
  }

  // ── .github/actions (Node.js and Ruby templates) ────────────────────────────

  const ACTIONS_DIR = join(ROOT, "shared", "ci", "actions");
  const ACTION_GEN_HEADER =
    "# Generated by scripts/commands/generate-configs.ts — edit shared/ci/actions/ instead.\n";

  // setup-node-yarn for Node.js templates
  const nodeTemplates = new Set([...NODE_VERSION_DIRS, ...Object.keys(FULL_CI_SOURCE)]);
  for (const dir of nodeTemplates) {
    const setupNodeYarnSrc = join(ACTIONS_DIR, "setup-node-yarn", "action.yml");
    const outActionDir = join(ROOT, dir, ".github", "actions", "setup-node-yarn");
    mkdirSync(outActionDir, { recursive: true });
    const actionContent = ACTION_GEN_HEADER + readFileSync(setupNodeYarnSrc, "utf8");
    writeFileSync(join(outActionDir, "action.yml"), actionContent, "utf8");
    console.log("Generated:", join(outActionDir, "action.yml"));
  }

  // setup-ruby-bundle for Ruby templates with test
  const rubyTestDirs = Object.keys(TEST_SOURCE).filter((dir) =>
    RUBY_VERSION_DIRS.includes(dir)
  );
  const rubyTemplates = new Set([...rubyTestDirs, ...Object.keys(FULL_TEST_SOURCE)]);
  for (const dir of rubyTemplates) {
    const setupRubyBundleSrc = join(ACTIONS_DIR, "setup-ruby-bundle", "action.yml");
    const outActionDir = join(ROOT, dir, ".github", "actions", "setup-ruby-bundle");
    mkdirSync(outActionDir, { recursive: true });
    const actionContent = ACTION_GEN_HEADER + readFileSync(setupRubyBundleSrc, "utf8");
    writeFileSync(join(outActionDir, "action.yml"), actionContent, "utf8");
    console.log("Generated:", join(outActionDir, "action.yml"));
  }

  // ── dependabot.yml ─────────────────────────────────────────────────────────

  const DEPENDABOT_SRC = join(WORKFLOWS_DIR, "dependabot.yml");
  const dependabotContent =
    "# Generated by scripts/commands/generate-configs.ts — edit shared/ci/workflows/dependabot.yml instead.\n" +
    readFileSync(DEPENDABOT_SRC, "utf8");

  for (const dir of [...TEMPLATE_DIRS, ...FULL_TEMPLATE_DIRS]) {
    const outDir = join(ROOT, dir, ".github");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "dependabot.yml");
    writeFileSync(outPath, dependabotContent, "utf8");
    console.log("Generated:", outPath);
  }
}
