/**
 * Generates ESLint, Prettier, tsconfig, Vitest configs for templates.
 * Refactored into modular functions for each tool.
 * Run via generate-configs.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { pathToFileURL } from 'url';
import { TEMPLATES_DIR } from '../lib/stacks.js';
import {
  ROOT,
  SHARED_CONFIG_STACKS,
  SHARED_ESLINT,
  SHARED_PRETTIER,
  SHARED_TSCONFIG,
  SHARED_VITEST,
} from '../lib/utils.js';
import { ensureFileExists, GenerationError } from '../lib/errors.js';
import { logger } from '../lib/logger.js';

const SHARED_MARKUPLINT = join(ROOT, 'shared', 'config', 'lint-format', 'markuplint');
const SHARED_MARKDOWNLINT = join(ROOT, 'shared', 'config', 'lint-format', 'markdownlint');
const SHARED_LIGHTHOUSE = join(ROOT, 'shared', 'extensions', 'lighthouse');
const SHARED_KNIP = join(ROOT, 'shared', 'extensions', 'knip');
const SHARED_PLAYWRIGHT = join(ROOT, 'shared', 'extensions', 'playwright');
const SHARED_MOCKS = join(ROOT, 'shared', 'config', 'test', 'mocks');

export const generateESLint = async (): Promise<void> => {
  logger.debug('Generating ESLint configs');
  const GEN_HEADER =
    '// Generated by scripts/commands/generate-configs.ts — edit shared/config/lint-format/eslint/eslint.config.<stack>.js instead.\n\n';
  const td = TEMPLATES_DIR;
  const ESLINT_SOURCE: Array<{ dir: string; source: string }> = [
    { dir: `${td}/nodejs`, source: 'eslint.config.nodejs.js' },
    { dir: `${td}/react`, source: 'eslint.config.react.js' },
    { dir: `${td}/nextjs`, source: 'eslint.config.nextjs.js' },
    { dir: `${td}/rails`, source: 'eslint.config.rails.js' },
    { dir: `${td}/rails-api`, source: 'eslint.config.rails.js' },
    { dir: 'full-templates/nextjs', source: 'eslint.config.nextjs-full.js' },
  ];

  for (const { dir, source } of ESLINT_SOURCE) {
    const sourcePath = join(SHARED_ESLINT, source);
    ensureFileExists(sourcePath, 'eslint');
    const stack = source.replace('eslint.config.', '').replace('.js', '');
    const content = GEN_HEADER.replace('<stack>', stack) + readFileSync(sourcePath, 'utf8');
    writeFileSync(join(ROOT, dir, 'eslint.config.js'), content, 'utf8');
    logger.generated(join(ROOT, dir, 'eslint.config.js'));
  }
}

export const generateVitest = async (): Promise<void> => {
  logger.debug('Generating Vitest configs');
  const GEN_HEADER =
    '// Generated by scripts/commands/generate-configs.ts — edit shared/config/test/vitest/ instead.\n\n';
  const td = TEMPLATES_DIR;
  const vitestNextjsEntries: Array<{
    dir: string;
    config: string;
    setup: string;
  }> = [
    {
      dir: `${td}/nextjs`,
      config: 'vitest.config.react-ts.minimal.ts',
      setup: 'vitest.setup.minimal.ts',
    },
    {
      dir: 'full-templates/nextjs',
      config: 'vitest.config.react-ts.ts',
      setup: 'vitest.setup.ts',
    },
  ];

  for (const { dir: vitestDir, config: configFile, setup: setupFile } of vitestNextjsEntries) {
    const configPath = join(SHARED_VITEST, configFile);
    const setupPath = join(SHARED_VITEST, setupFile);
    const envPath = join(SHARED_VITEST, 'vitest-env.d.ts');
    ensureFileExists(configPath, 'vitest');
    ensureFileExists(setupPath, 'vitest');
    ensureFileExists(envPath, 'vitest');

    writeFileSync(
      join(ROOT, vitestDir, 'vitest.config.ts'),
      GEN_HEADER + readFileSync(configPath, 'utf8'),
      'utf8',
    );
    logger.generated(join(ROOT, vitestDir, 'vitest.config.ts'));

    writeFileSync(
      join(ROOT, vitestDir, 'vitest.setup.ts'),
      GEN_HEADER + readFileSync(setupPath, 'utf8'),
      'utf8',
    );
    logger.generated(join(ROOT, vitestDir, 'vitest.setup.ts'));

    writeFileSync(
      join(ROOT, vitestDir, 'vitest-env.d.ts'),
      readFileSync(envPath, 'utf8'),
      'utf8',
    );
    logger.generated(join(ROOT, vitestDir, 'vitest-env.d.ts'));
  }
}

export const generatePrettier = async (): Promise<void> => {
  logger.debug('Generating Prettier configs');
  const prettierTsPath = join(SHARED_PRETTIER, '.prettierrc.ts');
  ensureFileExists(prettierTsPath, 'prettier');
  const prettierMod = await import(pathToFileURL(prettierTsPath).href);
  const prettierJson = JSON.stringify(prettierMod.default, null, 2);

  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, '.prettierrc.json');
    writeFileSync(outPath, prettierJson, 'utf8');
    logger.generated(outPath);
  }
}

export const generateTsconfig = async (): Promise<void> => {
  logger.debug('Generating tsconfig files');
  const td = TEMPLATES_DIR;

  // React configs
  const reactRootPath = join(SHARED_TSCONFIG, 'react', 'tsconfig.root.ts');
  const reactAppPath = join(SHARED_TSCONFIG, 'react', 'tsconfig.app.ts');
  const reactNodePath = join(SHARED_TSCONFIG, 'react', 'tsconfig.node.ts');
  ensureFileExists(reactRootPath, 'tsconfig-react');
  ensureFileExists(reactAppPath, 'tsconfig-react');
  ensureFileExists(reactNodePath, 'tsconfig-react');

  const reactRoot = await import(pathToFileURL(reactRootPath).href);
  const reactApp = await import(pathToFileURL(reactAppPath).href);
  const reactNode = await import(pathToFileURL(reactNodePath).href);

  writeFileSync(
    join(ROOT, td, 'react', 'tsconfig.json'),
    JSON.stringify(reactRoot.default, null, 2),
    'utf8',
  );
  logger.generated(join(ROOT, td, 'react', 'tsconfig.json'));

  writeFileSync(
    join(ROOT, td, 'react', 'tsconfig.app.json'),
    JSON.stringify(reactApp.default, null, 2),
    'utf8',
  );
  logger.generated(join(ROOT, td, 'react', 'tsconfig.app.json'));

  writeFileSync(
    join(ROOT, td, 'react', 'tsconfig.node.json'),
    JSON.stringify(reactNode.default, null, 2),
    'utf8',
  );
  logger.generated(join(ROOT, td, 'react', 'tsconfig.node.json'));

  // Next.js configs
  const nextjsTsMinimalPath = join(SHARED_TSCONFIG, 'nextjs', 'tsconfig.minimal.ts');
  const nextjsTsFullPath = join(SHARED_TSCONFIG, 'nextjs', 'tsconfig.ts');
  ensureFileExists(nextjsTsMinimalPath, 'tsconfig-nextjs');
  ensureFileExists(nextjsTsFullPath, 'tsconfig-nextjs');

  const nextjsTsMinimal = await import(pathToFileURL(nextjsTsMinimalPath).href);
  const nextjsTsFull = await import(pathToFileURL(nextjsTsFullPath).href);

  writeFileSync(
    join(ROOT, td, 'nextjs', 'tsconfig.json'),
    JSON.stringify(nextjsTsMinimal.default, null, 2),
    'utf8',
  );
  logger.generated(join(ROOT, td, 'nextjs', 'tsconfig.json'));

  writeFileSync(
    join(ROOT, 'full-templates/nextjs', 'tsconfig.json'),
    JSON.stringify(nextjsTsFull.default, null, 2),
    'utf8',
  );
  logger.generated(join(ROOT, 'full-templates/nextjs', 'tsconfig.json'));
}

export const generateMarkuplint = async (): Promise<void> => {
  logger.debug('Generating Markuplint configs');
  const markuplintPath = join(SHARED_MARKUPLINT, '.markuplintrc.react.json');
  ensureFileExists(markuplintPath, 'markuplint');

  const MARKUPLINT_DIRS = ['full-templates/nextjs'];
  for (const dir of MARKUPLINT_DIRS) {
    const outPath = join(ROOT, dir, '.markuplintrc.json');
    writeFileSync(outPath, readFileSync(markuplintPath, 'utf8'), 'utf8');
    logger.generated(outPath);
  }
}

export const generateMarkdownlint = async (): Promise<void> => {
  logger.debug('Generating Markdownlint configs');
  const markdownlintPath = join(SHARED_MARKDOWNLINT, '.markdownlint.json');
  ensureFileExists(markdownlintPath, 'markdownlint');

  const MARKDOWNLINT_DIRS = ['full-templates/nextjs'];
  for (const dir of MARKDOWNLINT_DIRS) {
    const outPath = join(ROOT, dir, '.markdownlint.json');
    writeFileSync(outPath, readFileSync(markdownlintPath, 'utf8'), 'utf8');
    logger.generated(outPath);
  }
}

export const generateLighthouse = async (): Promise<void> => {
  logger.debug('Generating Lighthouse configs');
  const lighthousePath = join(SHARED_LIGHTHOUSE, '.lighthouserc.js');
  ensureFileExists(lighthousePath, 'lighthouse');

  const LIGHTHOUSE_DIRS = ['full-templates/nextjs'];
  for (const dir of LIGHTHOUSE_DIRS) {
    const outPath = join(ROOT, dir, '.lighthouserc.js');
    writeFileSync(outPath, readFileSync(lighthousePath, 'utf8'), 'utf8');
    logger.generated(outPath);
  }
}

export const generateKnip = async (): Promise<void> => {
  logger.debug('Generating Knip configs');
  const knipPath = join(SHARED_KNIP, 'knip.config.nextjs.ts');
  ensureFileExists(knipPath, 'knip');
  const GEN_HEADER = '// Generated by scripts/commands/generate-configs.ts — edit shared/extensions/knip/ instead.\n\n';

  const KNIP_DIRS = ['full-templates/nextjs'];
  for (const dir of KNIP_DIRS) {
    const outPath = join(ROOT, dir, 'knip.config.ts');
    writeFileSync(outPath, GEN_HEADER + readFileSync(knipPath, 'utf8'), 'utf8');
    logger.generated(outPath);
  }
}

export const generatePlaywright = async (): Promise<void> => {
  logger.debug('Generating Playwright configs');
  const playwrightPath = join(SHARED_PLAYWRIGHT, 'playwright.config.nextjs.ts');
  ensureFileExists(playwrightPath, 'playwright');
  const GEN_HEADER =
    '// Generated by scripts/commands/generate-configs.ts — edit shared/extensions/playwright/ instead.\n\n';
  const PLAYWRIGHT_SPECS_SOURCE = join(SHARED_PLAYWRIGHT, 'specs');

  const PLAYWRIGHT_DIRS = ['full-templates/nextjs'];
  for (const dir of PLAYWRIGHT_DIRS) {
    const outPath = join(ROOT, dir, 'playwright.config.ts');
    writeFileSync(outPath, GEN_HEADER + readFileSync(playwrightPath, 'utf8'), 'utf8');
    logger.generated(outPath);

    // tests/e2e/specs ディレクトリ作成とサンプル spec コピー
    const e2eDir = join(ROOT, dir, 'tests', 'e2e', 'specs');
    mkdirSync(e2eDir, { recursive: true });
    if (existsSync(PLAYWRIGHT_SPECS_SOURCE)) {
      const specFiles = readdirSync(PLAYWRIGHT_SPECS_SOURCE) as string[];
      for (const file of specFiles.filter((f: string) => f.endsWith('.spec.ts'))) {
        const content = readFileSync(join(PLAYWRIGHT_SPECS_SOURCE, file), 'utf8');
        writeFileSync(join(e2eDir, file), content, 'utf8');
        logger.generated(join(dir, 'tests', 'e2e', 'specs', file));
      }
    }
  }
}

export const generateMocks = async (): Promise<void> => {
  logger.debug('Generating MSW mocks');
  const MOCKS_DIRS = ['full-templates/nextjs'];
  const GEN_HEADER =
    '// Generated by scripts/commands/generate-configs.ts — edit shared/config/test/mocks/ instead.\n\n';

  for (const dir of MOCKS_DIRS) {
    const mocksOut = join(ROOT, dir, 'src', 'mocks');
    mkdirSync(mocksOut, { recursive: true });
    for (const file of ['handlers.ts', 'server.ts']) {
      const mocksFilePath = join(SHARED_MOCKS, file);
      ensureFileExists(mocksFilePath, 'mocks');
      const content = readFileSync(mocksFilePath, 'utf8');
      writeFileSync(join(mocksOut, file), GEN_HEADER + content, 'utf8');
      logger.generated(join(dir, 'src', 'mocks', file));
    }
  }
}

export async function run(): Promise<void> {
  try {
    logger.start('Tool Configs Generation');

    // Generate configs concurrently where possible
    // Group 1: Independent tool configs (can run in parallel)
    await Promise.all([generateESLint(), generatePrettier()]);

    // Group 2: Template-specific configs (sequential to avoid conflicts)
    await generateVitest();
    await generateTsconfig();

    // Group 3: Markup/format tools (can run in parallel)
    await Promise.all([generateMarkuplint(), generateMarkdownlint(), generateLighthouse()]);

    // Group 4: Advanced tools (can run in parallel)
    await Promise.all([generateKnip(), generatePlaywright(), generateMocks()]);

    logger.end('Tool Configs Generation');
  } catch (error) {
    if (error instanceof GenerationError) {
      logger.error(`${error.message}`, error);
    } else if (error instanceof Error) {
      logger.error(`Tool config generation failed: ${error.message}`, error);
    } else {
      logger.error('Unknown error during tool config generation');
    }
    process.exit(1);
  }
}
