// Generated by scripts/generate-configs.ts — edit shared/knip/ instead.

/**
 * Knip 設定（Next.js テンプレート用）
 *
 * 未使用のエクスポート・依存関係を検出
 * @see https://knip.dev/
 */

import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    'src/app/**/*.{ts,tsx}',
    'src/components/**/*.{ts,tsx}',
    'src/config/env.ts',
    'src/config/sentry.config.ts',
    'src/instrumentation.ts',
    'src/lib/**/*.{ts,tsx}',
    'src/styles/**/*.{ts,tsx,css}',
    'src/hooks/**/*.{ts,tsx}',
    'src/utils/**/*.{ts,tsx}',
    'src/pages/**/*.{ts,tsx}',
    'src/**/*.stories.{ts,tsx}',
    'sentry.*.config.ts',
  ],
  eslint: true,
  husky: true,
  ignore: [
    '.next/**',
    'out/**',
    'dist/**',
    'build/**',
    'coverage/**',
    '.storybook/**',
    'src/config/path.ts',
  ],
  ignoreDependencies: [
    '@dotenvx/dotenvx',
    '@markuplint/jsx-parser',
    '@markuplint/react-spec',
    '@sentry/nextjs',
    '@secretlint/secretlint-rule-preset-recommend',
    'eslint-config-next',
    'lint-staged',
    'ts-node',
    'webpack-bundle-analyzer',
  ],
  playwright: true,
  prettier: true,
  project: ['src/**/*.{ts,tsx}', 'sentry.*.config.ts'],
  storybook: true,
  vitest: true,
};

export default config;
