// Generated by scripts/commands/generate-configs.ts — edit shared/config/test/vitest/ instead.

import '@testing-library/jest-dom/vitest';
import 'vitest-axe/extend-expect';
import { afterAll, afterEach, beforeAll, vi } from 'vitest';

import { server } from './src/mocks/server';

// next/font/google のモック（named exports 対応）
vi.mock('next/font/google', () => {
  const mock = vi.fn((config: { variable?: string }) => ({
    variable: config?.variable ?? '--font-mock',
    className: 'mock-font',
  }));
  return new Proxy(
    {},
    {
      get(_, prop) {
        if (prop === '__esModule') return true;
        return mock;
      },
    },
  );
});

// next/font/local のモック
vi.mock('next/font/local', () => ({
  default: vi.fn((config: { variable: string }) => ({
    variable: config.variable,
    className: `mock-${config.variable.replace('--', '')}`,
  })),
}));

// window.matchMedia のモック
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: vi.fn().mockImplementation((query: string) => ({
    addEventListener: vi.fn(),
    addListener: vi.fn(),
    dispatchEvent: vi.fn(),
    matches: false,
    media: query,
    onchange: null,
    removeEventListener: vi.fn(),
    removeListener: vi.fn(),
  })),
});

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
