// Generated by scripts/commands/generate-configs.ts — edit shared/config/lint-format/eslint/eslint.config.nodejs.js instead.

import js from "@eslint/js";
import globals from "globals";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },
  eslintConfigPrettier,
];
