// Generated by scripts/generate-configs.ts — edit shared/sentry/ instead.

/**
 * Next.js Instrumentation Hook
 *
 * この関数は Next.js サーバーの起動時に自動的に呼び出されます。
 * Sentry の Server-side 初期化に使用されます。
 *
 * @see https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation
 */

export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    // Server-side Sentry initialization
    await import('./config/sentry.config');
  }
}
