// Generated by scripts/commands/generate-configs.ts — edit shared/config/test/mocks/ instead.

/**
 * MSW メインハンドラー設定
 *
 * テスト・開発環境で使用するAPIモックハンドラー
 * アプリ固有のハンドラーをここに追加する
 */

export const handlers = [];
