inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 8.1
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  SuggestExtensions: false

# Override style rules as needed
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

FactoryBot/SyntaxMethods:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*
    - spec/features/**/*

RSpec/MultipleExpectations:
  Enabled: true
