import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { ROOT } from '../lib/utils.js';
import {
  TEMPLATE_DIRS,
  FULL_TEMPLATE_DIRS,
  CODE_CHECK_SOURCE,
  FULL_CODE_CHECK_SOURCE,
  TEST_SOURCE,
  FULL_TEST_SOURCE,
  FULL_CI_SOURCE,
} from '../lib/stacks.js';

const WORKFLOWS_DIR = join(ROOT, 'shared', 'workflows');

const ALL_TEMPLATE_DIRS = [...TEMPLATE_DIRS, ...FULL_TEMPLATE_DIRS];

// ── ソースファイル存在確認 ────────────────────────────────────────────────────

describe('gen-workflows: ソースワークフローファイル', () => {
  const allCodeCheckSources = {
    ...CODE_CHECK_SOURCE,
    ...FULL_CODE_CHECK_SOURCE,
  };
  const uniqueCodeCheck = [...new Set(Object.values(allCodeCheckSources))];

  it.each(uniqueCodeCheck)(
    'shared/workflows/%s が存在する (code-check)',
    (name) => {
      expect(existsSync(join(WORKFLOWS_DIR, name))).toBe(true);
    },
  );

  const allTestSources = { ...TEST_SOURCE, ...FULL_TEST_SOURCE };
  const uniqueTest = [...new Set(Object.values(allTestSources))];

  it.each(uniqueTest)('shared/workflows/%s が存在する (test)', (name) => {
    expect(existsSync(join(WORKFLOWS_DIR, name))).toBe(true);
  });

  const uniqueCi = [...new Set(Object.values(FULL_CI_SOURCE))];

  it.each(uniqueCi)('shared/workflows/%s が存在する (ci)', (name) => {
    expect(existsSync(join(WORKFLOWS_DIR, name))).toBe(true);
  });

  it('shared/workflows/static-analysis.yml が存在する', () => {
    expect(existsSync(join(WORKFLOWS_DIR, 'static-analysis.yml'))).toBe(true);
  });

  it('shared/workflows/dependabot.yml が存在する', () => {
    expect(existsSync(join(WORKFLOWS_DIR, 'dependabot.yml'))).toBe(true);
  });
});

// ── 生成済み code-check.yml ──────────────────────────────────────────────────

describe('gen-workflows: 生成済み code-check.yml', () => {
  const allDirs = Object.keys({
    ...CODE_CHECK_SOURCE,
    ...FULL_CODE_CHECK_SOURCE,
  });

  it.each(allDirs)('%s/.github/workflows/code-check.yml が存在する', (dir) => {
    expect(
      existsSync(join(ROOT, dir, '.github', 'workflows', 'code-check.yml')),
    ).toBe(true);
  });

  it.each(allDirs)(
    '%s/.github/workflows/code-check.yml が生成ヘッダーを持つ',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'code-check.yml'),
        'utf8',
      );
      expect(content).toContain('# Generated by scripts/generate-configs.ts');
    },
  );

  it.each(allDirs)(
    '%s/.github/workflows/code-check.yml に on: が含まれる',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'code-check.yml'),
        'utf8',
      );
      expect(content).toContain('on:');
    },
  );

  it.each(allDirs)(
    '%s/.github/workflows/code-check.yml に jobs: が含まれる',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'code-check.yml'),
        'utf8',
      );
      expect(content).toContain('jobs:');
    },
  );
});

// ── 生成済み test.yml ────────────────────────────────────────────────────────

describe('gen-workflows: 生成済み test.yml', () => {
  const allTestDirs = Object.keys({ ...TEST_SOURCE, ...FULL_TEST_SOURCE });

  it.each(allTestDirs)('%s/.github/workflows/test.yml が存在する', (dir) => {
    expect(
      existsSync(join(ROOT, dir, '.github', 'workflows', 'test.yml')),
    ).toBe(true);
  });

  it.each(allTestDirs)(
    '%s/.github/workflows/test.yml が生成ヘッダーを持つ',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'test.yml'),
        'utf8',
      );
      expect(content).toContain('# Generated by scripts/generate-configs.ts');
    },
  );

  it.each(allTestDirs)(
    '%s/.github/workflows/test.yml に jobs: が含まれる',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'test.yml'),
        'utf8',
      );
      expect(content).toContain('jobs:');
    },
  );
});

// ── 生成済み static-analysis.yml ────────────────────────────────────────────

describe('gen-workflows: 生成済み static-analysis.yml', () => {
  it.each(ALL_TEMPLATE_DIRS)(
    '%s/.github/workflows/static-analysis.yml が存在する',
    (dir) => {
      expect(
        existsSync(
          join(ROOT, dir, '.github', 'workflows', 'static-analysis.yml'),
        ),
      ).toBe(true);
    },
  );

  it.each(ALL_TEMPLATE_DIRS)(
    '%s/.github/workflows/static-analysis.yml が生成ヘッダーを持つ',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'workflows', 'static-analysis.yml'),
        'utf8',
      );
      expect(content).toContain('# Generated by scripts/generate-configs.ts');
    },
  );
});

// ── 生成済み dependabot.yml ──────────────────────────────────────────────────

describe('gen-workflows: 生成済み dependabot.yml', () => {
  it.each(ALL_TEMPLATE_DIRS)('%s/.github/dependabot.yml が存在する', (dir) => {
    expect(existsSync(join(ROOT, dir, '.github', 'dependabot.yml'))).toBe(true);
  });

  it.each(ALL_TEMPLATE_DIRS)(
    '%s/.github/dependabot.yml が生成ヘッダーを持つ',
    (dir) => {
      const content = readFileSync(
        join(ROOT, dir, '.github', 'dependabot.yml'),
        'utf8',
      );
      expect(content).toContain('# Generated by scripts/generate-configs.ts');
    },
  );

  it('全テンプレートの dependabot.yml が同一内容である', () => {
    const contents = ALL_TEMPLATE_DIRS.map((dir) =>
      readFileSync(join(ROOT, dir, '.github', 'dependabot.yml'), 'utf8'),
    );
    const first = contents[0];
    for (const c of contents.slice(1)) {
      expect(c).toBe(first);
    }
  });
});

// ── 生成済み ci.yml (full-templates のみ) ────────────────────────────────────

describe('gen-workflows: 生成済み ci.yml (full-templates)', () => {
  const ciDirs = Object.keys(FULL_CI_SOURCE);

  it.each(ciDirs)('%s/.github/workflows/ci.yml が存在する', (dir) => {
    expect(existsSync(join(ROOT, dir, '.github', 'workflows', 'ci.yml'))).toBe(
      true,
    );
  });

  it.each(ciDirs)('%s/.github/workflows/ci.yml が生成ヘッダーを持つ', (dir) => {
    const content = readFileSync(
      join(ROOT, dir, '.github', 'workflows', 'ci.yml'),
      'utf8',
    );
    expect(content).toContain('# Generated by scripts/generate-configs.ts');
  });
});

// ── test.yml を持たないテンプレートの確認 ───────────────────────────────────

describe('gen-workflows: test.yml のないテンプレート', () => {
  const withTest = new Set(Object.keys(TEST_SOURCE));
  const withoutTest = [...TEMPLATE_DIRS].filter((dir) => !withTest.has(dir));

  it('testWorkflow 未定義のテンプレートが存在する（ruby のみ）', () => {
    expect(withoutTest.length).toBeGreaterThan(0);
  });

  it.each(withoutTest)('%s に test.yml が生成されていない', (dir) => {
    expect(
      existsSync(join(ROOT, dir, '.github', 'workflows', 'test.yml')),
    ).toBe(false);
  });
});
