import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import {
  ROOT,
  SHARED_CONFIG_STACKS,
  SHARED_ESLINT,
  SHARED_PRETTIER,
  SHARED_VITEST,
  SHARED_TSCONFIG,
} from '../lib/utils.js';
import { TEMPLATES_DIR } from '../lib/stacks.js';
import { ESLINT_SOURCE } from '../generate-tool-configs.js';

const td = TEMPLATES_DIR;

describe('gen-tool-configs: ESLint ソースファイル', () => {
  it.each(ESLINT_SOURCE)(
    '$source が shared/lint-format/eslint/ に存在する',
    ({ source }) => {
      expect(existsSync(join(SHARED_ESLINT, source))).toBe(true);
    },
  );
});

describe('gen-tool-configs: 生成済み ESLint 設定', () => {
  it.each(ESLINT_SOURCE)('$dir/eslint.config.js が存在する', ({ dir }) => {
    expect(existsSync(join(ROOT, dir, 'eslint.config.js'))).toBe(true);
  });

  it.each(ESLINT_SOURCE)(
    '$dir/eslint.config.js が生成ヘッダーで始まる',
    ({ dir }) => {
      const content = readFileSync(join(ROOT, dir, 'eslint.config.js'), 'utf8');
      expect(content).toContain('// Generated by scripts/generate-configs.ts');
    },
  );

  it.each(ESLINT_SOURCE)(
    '$dir/eslint.config.js がヘッダー以外の内容を持つ',
    ({ dir }) => {
      const content = readFileSync(join(ROOT, dir, 'eslint.config.js'), 'utf8');
      const lines = content
        .split('\n')
        .filter((l) => l.trim() && !l.startsWith('//'));
      expect(lines.length).toBeGreaterThan(0);
    },
  );
});

// ── Prettier ─────────────────────────────────────────────────────────────────

describe('gen-tool-configs: Prettier ソースファイル', () => {
  it('.prettierrc.ts が shared/lint-format/prettier/ に存在する', () => {
    expect(existsSync(join(SHARED_PRETTIER, '.prettierrc.ts'))).toBe(true);
  });
});

describe('gen-tool-configs: 生成済み Prettier 設定', () => {
  it.each([...SHARED_CONFIG_STACKS])(
    '%s/.prettierrc.json が存在する',
    (dir) => {
      expect(existsSync(join(ROOT, dir, '.prettierrc.json'))).toBe(true);
    },
  );

  it.each([...SHARED_CONFIG_STACKS])(
    '%s/.prettierrc.json が有効な JSON である',
    (dir) => {
      const raw = readFileSync(join(ROOT, dir, '.prettierrc.json'), 'utf8');
      expect(() => JSON.parse(raw)).not.toThrow();
    },
  );

  it.each([...SHARED_CONFIG_STACKS])(
    '%s/.prettierrc.json が必須キーを持つ',
    (dir) => {
      const config = JSON.parse(
        readFileSync(join(ROOT, dir, '.prettierrc.json'), 'utf8'),
      ) as Record<string, unknown>;
      expect(config).toHaveProperty('semi');
      expect(config).toHaveProperty('singleQuote');
      expect(config).toHaveProperty('printWidth');
      expect(config).toHaveProperty('tabWidth');
    },
  );

  it('全テンプレートの .prettierrc.json が同一内容である', () => {
    const contents = [...SHARED_CONFIG_STACKS].map((dir) =>
      readFileSync(join(ROOT, dir, '.prettierrc.json'), 'utf8'),
    );
    const first = contents[0];
    for (const c of contents.slice(1)) {
      expect(c).toBe(first);
    }
  });
});

// ── Vitest ───────────────────────────────────────────────────────────────────

const VITEST_ENTRIES = [
  {
    dir: `${td}/nextjs`,
    config: 'vitest.config.react-ts.minimal.ts',
    setup: 'vitest.setup.minimal.ts',
  },
  {
    dir: 'full-templates/nextjs',
    config: 'vitest.config.react-ts.ts',
    setup: 'vitest.setup.ts',
  },
];

describe('gen-tool-configs: Vitest ソースファイル', () => {
  it.each(VITEST_ENTRIES)(
    '$config が shared/test/vitest/ に存在する',
    ({ config }) => {
      expect(existsSync(join(SHARED_VITEST, config))).toBe(true);
    },
  );

  it.each(VITEST_ENTRIES)(
    '$setup が shared/test/vitest/ に存在する',
    ({ setup }) => {
      expect(existsSync(join(SHARED_VITEST, setup))).toBe(true);
    },
  );

  it('vitest-env.d.ts が shared/test/vitest/ に存在する', () => {
    expect(existsSync(join(SHARED_VITEST, 'vitest-env.d.ts'))).toBe(true);
  });
});

describe('gen-tool-configs: 生成済み Vitest 設定', () => {
  it.each(VITEST_ENTRIES)('$dir/vitest.config.ts が存在する', ({ dir }) => {
    expect(existsSync(join(ROOT, dir, 'vitest.config.ts'))).toBe(true);
  });

  it.each(VITEST_ENTRIES)(
    '$dir/vitest.config.ts が生成ヘッダーで始まる',
    ({ dir }) => {
      const content = readFileSync(join(ROOT, dir, 'vitest.config.ts'), 'utf8');
      expect(content).toContain('// Generated by scripts/generate-configs.ts');
    },
  );

  it.each(VITEST_ENTRIES)('$dir/vitest.setup.ts が存在する', ({ dir }) => {
    expect(existsSync(join(ROOT, dir, 'vitest.setup.ts'))).toBe(true);
  });

  it.each(VITEST_ENTRIES)('$dir/vitest-env.d.ts が存在する', ({ dir }) => {
    expect(existsSync(join(ROOT, dir, 'vitest-env.d.ts'))).toBe(true);
  });
});

// ── tsconfig ─────────────────────────────────────────────────────────────────

const TSCONFIG_REACT_SOURCES = [
  'react/tsconfig.root.ts',
  'react/tsconfig.app.ts',
  'react/tsconfig.node.ts',
];
const TSCONFIG_NEXTJS_SOURCES = [
  'nextjs/tsconfig.minimal.ts',
  'nextjs/tsconfig.ts',
];

describe('gen-tool-configs: tsconfig ソースファイル', () => {
  it.each(TSCONFIG_REACT_SOURCES)(
    '%s が shared/tsconfig/ に存在する',
    (src) => {
      expect(existsSync(join(SHARED_TSCONFIG, src))).toBe(true);
    },
  );

  it.each(TSCONFIG_NEXTJS_SOURCES)(
    '%s が shared/tsconfig/ に存在する',
    (src) => {
      expect(existsSync(join(SHARED_TSCONFIG, src))).toBe(true);
    },
  );
});

describe('gen-tool-configs: 生成済み tsconfig', () => {
  const TSCONFIG_FILES = [
    { path: `${td}/react/tsconfig.json` },
    { path: `${td}/react/tsconfig.app.json` },
    { path: `${td}/react/tsconfig.node.json` },
    { path: `${td}/nextjs/tsconfig.json` },
    { path: 'full-templates/nextjs/tsconfig.json' },
  ];

  it.each(TSCONFIG_FILES)('$path が存在する', ({ path }) => {
    expect(existsSync(join(ROOT, path))).toBe(true);
  });

  it.each(TSCONFIG_FILES)('$path が有効な JSON である', ({ path }) => {
    const raw = readFileSync(join(ROOT, path), 'utf8');
    expect(() => JSON.parse(raw)).not.toThrow();
  });

  it.each(TSCONFIG_FILES)('$path が compilerOptions を持つ', ({ path }) => {
    const config = JSON.parse(readFileSync(join(ROOT, path), 'utf8')) as Record<
      string,
      unknown
    >;
    // tsconfig.json (root) は references を持つ場合がある
    const hasCompilerOptions = 'compilerOptions' in config;
    const hasReferences = 'references' in config;
    expect(hasCompilerOptions || hasReferences).toBe(true);
  });

  it('minimal nextjs の tsconfig は strict が有効である', () => {
    const config = JSON.parse(
      readFileSync(join(ROOT, `${td}/nextjs/tsconfig.json`), 'utf8'),
    ) as { compilerOptions?: { strict?: boolean } };
    expect(config.compilerOptions?.strict).toBe(true);
  });
});
