AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - Rakefile
    - spec/**/*
Style/FrozenStringLiteralComment:
  Enabled: false
