AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
    - node_modules/**/*
    - public/**/*
    - tmp/**/*
    - log/**/*
    - storage/**/*
    - coverage/**/*
    - spec/support/**/*
    - spec/fixtures/**/*
    - spec/factories/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
Style/Documentation:
  Enabled: false
require:
  - rubocop-rails
  - rubocop-rspec
inherit_mode:
  merge:
    - Exclude
Rails:
  Enabled: true
RSpec:
  Enabled: true
