/**
 * Generates pint.json and phpunit.xml for Laravel template.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { ROOT, SHARED_LARAVEL } from "./lib/utils.js";

const LARAVEL_TEMPLATE = join(ROOT, "templates", "laravel");

const PHPUNIT_HEADER =
  "<!-- Generated by scripts/gen-laravel-configs.ts — edit shared/framework/laravel/ instead. -->\n";

export function run(): void {
  // ── pint.json（shared → templates/laravel）────────────────────────────────

  const pintContent = readFileSync(join(SHARED_LARAVEL, "pint.json"), "utf8");
  writeFileSync(join(LARAVEL_TEMPLATE, "pint.json"), pintContent + "\n", "utf8");
  console.log("Generated:", join(LARAVEL_TEMPLATE, "pint.json"));

  // ── phpunit.xml（shared → templates/laravel、先頭に生成コメントを付与）────

  const phpunitRaw = readFileSync(join(SHARED_LARAVEL, "phpunit.xml"), "utf8");
  const phpunitContent =
    phpunitRaw.startsWith("<?xml")
      ? phpunitRaw.replace("?>", "?>\n" + PHPUNIT_HEADER)
      : PHPUNIT_HEADER + phpunitRaw;
  writeFileSync(join(LARAVEL_TEMPLATE, "phpunit.xml"), phpunitContent, "utf8");
  console.log("Generated:", join(LARAVEL_TEMPLATE, "phpunit.xml"));
}
