/**
 * Generates GitHub Actions workflows and dependabot.yml for templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { ROOT } from './lib/utils.js';
import { logger } from './lib/logger.js';
import { GenerationError } from './lib/errors.js';
import {
  TEMPLATE_DIRS,
  FULL_TEMPLATE_DIRS,
  CODE_CHECK_SOURCE,
  FULL_CODE_CHECK_SOURCE,
  TEST_SOURCE,
  FULL_TEST_SOURCE,
  FULL_CI_SOURCE,
} from './lib/stacks.js';

export function run(): void {
  try {
    const WORKFLOWS_DIR = join(ROOT, 'shared', 'workflows');
    const GEN_HEADER =
      '# Generated by scripts/generate-configs.ts — edit shared/workflows/<name> instead.\n';

    // ── static-analysis.yml ────────────────────────────────────────────────────

    const STATIC_ANALYSIS_SRC = join(WORKFLOWS_DIR, 'static-analysis.yml');
    const STATIC_ANALYSIS_HEADER =
      '# Generated by scripts/generate-configs.ts — edit shared/workflows/static-analysis.yml instead.\n';
    const staticAnalysisContent =
      STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, 'utf8');

    for (const dir of [...TEMPLATE_DIRS, ...FULL_TEMPLATE_DIRS]) {
      const outDir = join(ROOT, dir, '.github', 'workflows');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'static-analysis.yml');
      writeFileSync(outPath, staticAnalysisContent, 'utf8');
      logger.generated(outPath);
    }

    // ── code-check.yml ─────────────────────────────────────────────────────────

    for (const [dir, srcName] of Object.entries({
      ...CODE_CHECK_SOURCE,
      ...FULL_CODE_CHECK_SOURCE,
    })) {
      const srcPath = join(WORKFLOWS_DIR, srcName);
      const content =
        GEN_HEADER.replace('<name>', srcName) + readFileSync(srcPath, 'utf8');
      const outDir = join(ROOT, dir, '.github', 'workflows');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'code-check.yml');
      writeFileSync(outPath, content, 'utf8');
      logger.generated(outPath);
    }

    // ── test.yml ───────────────────────────────────────────────────────────────

    for (const [dir, srcName] of Object.entries({
      ...TEST_SOURCE,
      ...FULL_TEST_SOURCE,
    })) {
      const srcPath = join(WORKFLOWS_DIR, srcName);
      const content =
        GEN_HEADER.replace('<name>', srcName) + readFileSync(srcPath, 'utf8');
      const outDir = join(ROOT, dir, '.github', 'workflows');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'test.yml');
      writeFileSync(outPath, content, 'utf8');
      logger.generated(outPath);
    }

    // ── ci.yml ─────────────────────────────────────────────────────────────────

    for (const [dir, srcName] of Object.entries(FULL_CI_SOURCE)) {
      const srcPath = join(WORKFLOWS_DIR, srcName);
      const content =
        GEN_HEADER.replace('<name>', srcName) + readFileSync(srcPath, 'utf8');
      const outDir = join(ROOT, dir, '.github', 'workflows');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'ci.yml');
      writeFileSync(outPath, content, 'utf8');
      logger.generated(outPath);
    }

    // ── ci-e2e-nextjs.yml / ci-lighthouse-nextjs.yml (reusable, full-templates with CI only) ──

    const CI_REUSABLE_WORKFLOWS = [
      'ci-e2e-nextjs.yml',
      'ci-lighthouse-nextjs.yml',
    ];
    for (const dir of Object.keys(FULL_CI_SOURCE)) {
      const outDir = join(ROOT, dir, '.github', 'workflows');
      mkdirSync(outDir, { recursive: true });
      for (const srcName of CI_REUSABLE_WORKFLOWS) {
        const content =
          GEN_HEADER.replace('<name>', srcName) +
          readFileSync(join(WORKFLOWS_DIR, srcName), 'utf8');
        writeFileSync(join(outDir, srcName), content, 'utf8');
        logger.generated(join(outDir, srcName));
      }
    }

    // ── .github/actions (full-templates with CI only) ──────────────────────────

    const ACTIONS_DIR = join(ROOT, 'shared', 'actions');
    const ACTION_GEN_HEADER =
      '# Generated by scripts/generate-configs.ts — edit shared/actions/ instead.\n';
    for (const dir of Object.keys(FULL_CI_SOURCE)) {
      const setupNodeYarnSrc = join(
        ACTIONS_DIR,
        'setup-node-yarn',
        'action.yml',
      );
      const outActionDir = join(
        ROOT,
        dir,
        '.github',
        'actions',
        'setup-node-yarn',
      );
      mkdirSync(outActionDir, { recursive: true });
      const actionContent =
        ACTION_GEN_HEADER + readFileSync(setupNodeYarnSrc, 'utf8');
      writeFileSync(join(outActionDir, 'action.yml'), actionContent, 'utf8');
      logger.generated(join(outActionDir, 'action.yml'));
    }

    // ── dependabot.yml ─────────────────────────────────────────────────────────

    const DEPENDABOT_SRC = join(WORKFLOWS_DIR, 'dependabot.yml');
    const dependabotContent =
      '# Generated by scripts/generate-configs.ts — edit shared/workflows/dependabot.yml instead.\n' +
      readFileSync(DEPENDABOT_SRC, 'utf8');

    for (const dir of [...TEMPLATE_DIRS, ...FULL_TEMPLATE_DIRS]) {
      const outDir = join(ROOT, dir, '.github');
      mkdirSync(outDir, { recursive: true });
      const outPath = join(outDir, 'dependabot.yml');
      writeFileSync(outPath, dependabotContent, 'utf8');
      logger.generated(outPath);
    }
  } catch (error) {
    if (error instanceof GenerationError) {
      console.error(`\n❌ ${error.message}`);
      console.error(`   Context: ${error.context}`);
    } else if (error instanceof Error) {
      console.error(`\n❌ Unexpected error: ${error.message}`);
      console.error(error.stack);
    } else {
      console.error('\n❌ Unknown error occurred');
    }
    process.exit(1);
  }
}
