/**
 * Generates .editorconfig, .gitignore, .node-version, .ruby-version for all templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import {
  ROOT,
  VERSIONS,
  SHARED_CONFIG_STACKS,
  SHARED_EDITORCONFIG,
  GITIGNORE_DIR,
} from "./lib/utils.js";

export function run(): void {
  // templates/go, templates/rust は generate-deps で中身が作られるが .gitignore 等はここで書くので先にディレクトリを作成
  mkdirSync(join(ROOT, "templates", "go"), { recursive: true });
  mkdirSync(join(ROOT, "templates", "rust"), { recursive: true });

  // ── .editorconfig（shared からコピー）──────────────────────────────────────────

  const editorconfigContent = readFileSync(SHARED_EDITORCONFIG, "utf8");
  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, ".editorconfig");
    writeFileSync(outPath, editorconfigContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .dockerignore（shared/docker から Rails / Rails API 用にコピー）────────────

  const DOCKER_DIR = join(ROOT, "shared", "docker");
  const DOCKERIGNORE_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/docker/ instead.\n\n";
  const DOCKERIGNORE_SOURCE: Record<string, string> = {
    "templates/rails": "dockerignore.rails",
    "templates/rails-api": "dockerignore.rails-api",
  };
  for (const [dir, srcName] of Object.entries(DOCKERIGNORE_SOURCE)) {
    const srcPath = join(DOCKER_DIR, srcName);
    const content = DOCKERIGNORE_HEADER + readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, dir, ".dockerignore");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .gitignore（shared/gitignore からスタック別にコピー）────────────────────────

  const GITIGNORE_SOURCE: Record<string, string> = {
    "templates/nextjs": ".gitignore.node",
    "templates/nodejs": ".gitignore.node",
    "templates/reactjs": ".gitignore.node",
    "templates/rails": ".gitignore.rails",
    "templates/rails-api": ".gitignore.rails",
    "templates/sinatra": ".gitignore.ruby",
    "templates/csharp": ".gitignore.dotnet",
    "templates/go": ".gitignore.go",
    "templates/rust": ".gitignore.rust",
  };

  const GITIGNORE_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/gitignore/ instead.\n\n";
  for (const [dir, srcName] of Object.entries(GITIGNORE_SOURCE)) {
    const srcPath = join(GITIGNORE_DIR, srcName);
    const content = GITIGNORE_HEADER + readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, dir, ".gitignore");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .ruby-version（shared/versions.json から生成）──────────────────────────────

  const RUBY_VERSION_DIRS = ["templates/rails", "templates/rails-api", "templates/sinatra"];
  for (const dir of RUBY_VERSION_DIRS) {
    const outPath = join(ROOT, dir, ".ruby-version");
    writeFileSync(outPath, VERSIONS.ruby + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  // ── .node-version（shared/versions.json から生成）──────────────────────────────

  const NODE_VERSION_DIRS = ["templates/nextjs", "templates/nodejs", "templates/reactjs", "templates/rails", "templates/rails-api", "templates/sinatra"];
  for (const dir of NODE_VERSION_DIRS) {
    const outPath = join(ROOT, dir, ".node-version");
    writeFileSync(outPath, VERSIONS.node + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  // ── .go-version（shared/versions.json から生成）────────────────────────────────

  if (VERSIONS.go) {
    const outPath = join(ROOT, "templates/go", ".go-version");
    writeFileSync(outPath, VERSIONS.go + "\n", "utf8");
    console.log("Generated:", outPath);
  }
}
