/**
 * Generates .editorconfig, .gitignore, .node-version, .ruby-version for all templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import {
  ROOT,
  VERSIONS,
  SHARED_CONFIG_STACKS,
  SHARED_EDITORCONFIG,
  GITIGNORE_DIR,
} from "./lib/utils.js";
import {
  DOCKERIGNORE_SOURCE,
  GITIGNORE_SOURCE,
  GO_VERSION_DIRS,
  NODE_VERSION_DIRS,
  PHP_VERSION_DIRS,
  PYTHON_VERSION_DIRS,
  RUBY_VERSION_DIRS,
} from "./lib/stacks.js";

export function run(): void {
  // templates/go, templates/rust, templates/django は generate-deps で中身が作られないため .gitignore 等はここで書くので先にディレクトリを作成
  mkdirSync(join(ROOT, "templates", "go"), { recursive: true });
  mkdirSync(join(ROOT, "templates", "rust"), { recursive: true });
  mkdirSync(join(ROOT, "templates", "django"), { recursive: true });
  mkdirSync(join(ROOT, "templates", "laravel"), { recursive: true });

  // ── .editorconfig（shared からコピー）──────────────────────────────────────────

  const editorconfigContent = readFileSync(SHARED_EDITORCONFIG, "utf8");
  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, ".editorconfig");
    writeFileSync(outPath, editorconfigContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .dockerignore（shared/docker から Rails / Rails API 用にコピー）────────────

  const DOCKER_DIR = join(ROOT, "shared", "docker");
  const DOCKERIGNORE_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/docker/ instead.\n\n";
  for (const [dir, srcName] of Object.entries(DOCKERIGNORE_SOURCE)) {
    const srcPath = join(DOCKER_DIR, srcName);
    const content = DOCKERIGNORE_HEADER + readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, dir, ".dockerignore");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .gitignore（shared/gitignore からスタック別にコピー）────────────────────────

  const GITIGNORE_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/gitignore/ instead.\n\n";
  for (const [dir, srcName] of Object.entries(GITIGNORE_SOURCE)) {
    const srcPath = join(GITIGNORE_DIR, srcName);
    const content = GITIGNORE_HEADER + readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, dir, ".gitignore");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .ruby-version（shared/versions.json から生成）──────────────────────────────

  for (const dir of RUBY_VERSION_DIRS) {
    const outPath = join(ROOT, dir, ".ruby-version");
    writeFileSync(outPath, VERSIONS.ruby + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  // ── .node-version（shared/versions.json から生成）──────────────────────────────

  for (const dir of NODE_VERSION_DIRS) {
    const outPath = join(ROOT, dir, ".node-version");
    writeFileSync(outPath, VERSIONS.node + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  // ── .php-version（shared/versions.json から生成）────────────────────────────────

  if (VERSIONS.php) {
    for (const dir of PHP_VERSION_DIRS) {
      const outPath = join(ROOT, dir, ".php-version");
      writeFileSync(outPath, VERSIONS.php + "\n", "utf8");
      console.log("Generated:", outPath);
    }
  }

  // ── .go-version（shared/versions.json から生成）────────────────────────────────

  if (VERSIONS.go) {
    for (const dir of GO_VERSION_DIRS) {
      const outPath = join(ROOT, dir, ".go-version");
      writeFileSync(outPath, VERSIONS.go + "\n", "utf8");
      console.log("Generated:", outPath);
    }
  }

  // ── .python-version（shared/versions.json から生成）────────────────────────────

  if (VERSIONS.python) {
    for (const dir of PYTHON_VERSION_DIRS) {
      const outPath = join(ROOT, dir, ".python-version");
      writeFileSync(outPath, VERSIONS.python + "\n", "utf8");
      console.log("Generated:", outPath);
    }
  }
}
