/**
 * Generates GitHub Actions workflows, dependabot.yml, and .env.* files for templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { ROOT } from "./lib/utils.js";

const STATIC_ANALYSIS_STACKS: string[] = [
  "templates/nextjs",
  "templates/nodejs",
  "templates/react",
  "templates/rails",
  "templates/rails-api",
  "templates/sinatra",
  "templates/csharp",
];

export function run(): void {
  const WORKFLOWS_DIR = join(ROOT, "shared", "workflows");
  const GEN_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/<name> instead.\n";

  // ── static-analysis.yml ────────────────────────────────────────────────────

  const STATIC_ANALYSIS_SRC = join(WORKFLOWS_DIR, "static-analysis.yml");
  const STATIC_ANALYSIS_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/static-analysis.yml instead.\n";
  const staticAnalysisContent = STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, "utf8");

  for (const dir of STATIC_ANALYSIS_STACKS) {
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "static-analysis.yml");
    writeFileSync(outPath, staticAnalysisContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── code-check.yml ─────────────────────────────────────────────────────────

  const CODE_CHECK_SOURCE: Record<string, string> = {
    "templates/nextjs": "code-check-node.yml",
    "templates/nodejs": "code-check-node.yml",
    "templates/react": "code-check-node.yml",
    "templates/rails-api": "code-check-ruby.yml",
    "templates/sinatra": "code-check-ruby-erb.yml",
    "templates/rails": "code-check-ruby-erb.yml",
    "templates/csharp": "code-check-dotnet.yml",
  };

  for (const [dir, srcName] of Object.entries(CODE_CHECK_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "code-check.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── test.yml ───────────────────────────────────────────────────────────────

  const TEST_SOURCE: Record<string, string> = {
    "templates/react": "test-node.yml",
    "templates/sinatra": "test-sinatra.yml",
    "templates/rails": "test-rails.yml",
    "templates/rails-api": "test-rails-api.yml",
    "templates/csharp": "test-dotnet.yml",
  };

  for (const [dir, srcName] of Object.entries(TEST_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "test.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── dependabot.yml ─────────────────────────────────────────────────────────

  const DEPENDABOT_SRC = join(WORKFLOWS_DIR, "dependabot.yml");
  const dependabotContent =
    "# Generated by scripts/generate-configs.ts — edit shared/workflows/dependabot.yml instead.\n" +
    readFileSync(DEPENDABOT_SRC, "utf8");

  for (const dir of STATIC_ANALYSIS_STACKS) {
    const outDir = join(ROOT, dir, ".github");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "dependabot.yml");
    writeFileSync(outPath, dependabotContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .env.example / .env.test / .env.development ───────────────────────────

  const SHARED_ENV = join(ROOT, "shared", "env");
  const DB_ENV_PATH = join(SHARED_ENV, "db.env");
  const ENV_TEMPLATES: Array<{ dir: string; variant: "rails" | "sinatra"; templateId: string }> = [
    { dir: "templates/rails-api", variant: "rails", templateId: "template-rails-api" },
    { dir: "templates/sinatra", variant: "sinatra", templateId: "template-sinatra" },
  ];

  const dbEnvContent = readFileSync(DB_ENV_PATH, "utf8");

  type EnvKind = "example" | "test" | "development";
  const ENV_KINDS: Array<{ kind: EnvKind; envValue: string; suffix: string }> = [
    { kind: "example", envValue: "development", suffix: "_development" },
    { kind: "test", envValue: "test", suffix: "_test" },
    { kind: "development", envValue: "development", suffix: "_development" },
  ];

  for (const { dir, variant, templateId } of ENV_TEMPLATES) {
    const headPath = join(SHARED_ENV, `${variant}.env.head`);
    const headTemplate = readFileSync(headPath, "utf8");

    for (const { kind, envValue, suffix } of ENV_KINDS) {
      const head = headTemplate.replace(/\{\{ENV\}\}/g, envValue);
      const db = dbEnvContent
        .replace(/\{\{TEMPLATE_ID\}\}/g, templateId)
        .replace(/\{\{SUFFIX\}\}/g, suffix);
      const content = head + db;
      const outPath = join(ROOT, dir, `.env.${kind}`);
      writeFileSync(outPath, content, "utf8");
      console.log("Generated:", outPath);
    }
  }
}
