/**
 * Generates ESLint, Prettier, tsconfig, Vitest configs for templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { pathToFileURL } from 'url';
import { TEMPLATES_DIR } from './lib/stacks.js';
import {
  ROOT,
  SHARED_CONFIG_STACKS,
  SHARED_ESLINT,
  SHARED_PRETTIER,
  SHARED_TSCONFIG,
  SHARED_VITEST,
} from './lib/utils.js';

const SHARED_MARKUPLINT = join(ROOT, 'shared', 'lint-format', 'markuplint');
const SHARED_LIGHTHOUSE = join(ROOT, 'shared', 'lighthouse');

export async function run(): Promise<void> {
  // ── ESLint ─────────────────────────────────────────────────────────────────

  const GEN_HEADER_ESLINT =
    '// Generated by scripts/generate-configs.ts — edit shared/lint-format/eslint/eslint.config.<stack>.js instead.\n\n';
  const td = TEMPLATES_DIR;
  const ESLINT_SOURCE: Array<{ dir: string; source: string }> = [
    { dir: `${td}/nodejs`, source: 'eslint.config.nodejs.js' },
    { dir: `${td}/reactjs`, source: 'eslint.config.react.js' },
    { dir: `${td}/nextjs`, source: 'eslint.config.nextjs.js' },
    { dir: `${td}/rails`, source: 'eslint.config.rails.js' },
    { dir: `${td}/rails-api`, source: 'eslint.config.rails.js' },
    { dir: 'full-templates/nextjs', source: 'eslint.config.nextjs.js' },
  ];
  for (const { dir, source } of ESLINT_SOURCE) {
    const stack = source.replace('eslint.config.', '').replace('.js', '');
    const content =
      GEN_HEADER_ESLINT.replace('<stack>', stack) +
      readFileSync(join(SHARED_ESLINT, source), 'utf8');
    writeFileSync(join(ROOT, dir, 'eslint.config.js'), content, 'utf8');
    console.log('Generated:', join(ROOT, dir, 'eslint.config.js'));
  }

  // ── Vitest ─────────────────────────────────────────────────────────────────

  const VITEST_HEADER =
    '// Generated by scripts/generate-configs.ts — edit shared/test/vitest/ instead.\n\n';
  const VITEST_NEXTJS_DIRS = [`${td}/nextjs`, 'full-templates/nextjs'];
  for (const vitestDir of VITEST_NEXTJS_DIRS) {
    writeFileSync(
      join(ROOT, vitestDir, 'vitest.config.ts'),
      VITEST_HEADER +
        readFileSync(join(SHARED_VITEST, 'vitest.config.react-ts.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest.config.ts'));
    writeFileSync(
      join(ROOT, vitestDir, 'vitest.setup.ts'),
      VITEST_HEADER +
        readFileSync(join(SHARED_VITEST, 'vitest.setup.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest.setup.ts'));
    writeFileSync(
      join(ROOT, vitestDir, 'vitest-env.d.ts'),
      readFileSync(join(SHARED_VITEST, 'vitest-env.d.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest-env.d.ts'));
  }

  // ── Prettier（.ts ソースから .json を生成）─────────────────────────────────

  const prettierMod = await import(
    pathToFileURL(join(SHARED_PRETTIER, '.prettierrc.ts')).href
  );
  const prettierJson = JSON.stringify(prettierMod.default, null, 2);
  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, '.prettierrc.json');
    writeFileSync(outPath, prettierJson, 'utf8');
    console.log('Generated:', outPath);
  }

  // ── tsconfig（.ts ソースから .json を生成）─────────────────────────────────

  const reactRoot = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.root.ts')).href
  );
  const reactApp = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.app.ts')).href
  );
  const reactNode = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.node.ts')).href
  );
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.json'),
    JSON.stringify(reactRoot.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.json'));
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.app.json'),
    JSON.stringify(reactApp.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.app.json'));
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.node.json'),
    JSON.stringify(reactNode.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.node.json'));

  const nextjsTs = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'nextjs', 'tsconfig.ts')).href
  );
  const TSCONFIG_NEXTJS_DIRS = [`${td}/nextjs`, 'full-templates/nextjs'];
  for (const tsconfigDir of TSCONFIG_NEXTJS_DIRS) {
    writeFileSync(
      join(ROOT, tsconfigDir, 'tsconfig.json'),
      JSON.stringify(nextjsTs.default, null, 2),
      'utf8',
    );
    console.log('Generated:', join(ROOT, tsconfigDir, 'tsconfig.json'));
  }

  // ── Markuplint (.markuplintrc.json) ────────────────────────────────────────

  const MARKUPLINT_REACT_DIRS = ['full-templates/nextjs'];
  for (const dir of MARKUPLINT_REACT_DIRS) {
    const outPath = join(ROOT, dir, '.markuplintrc.json');
    writeFileSync(
      outPath,
      readFileSync(join(SHARED_MARKUPLINT, '.markuplintrc.react.json'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
  }

  // ── Lighthouse CI (.lighthouserc.js) ──────────────────────────────────────

  const LIGHTHOUSE_DIRS = ['full-templates/nextjs'];
  for (const dir of LIGHTHOUSE_DIRS) {
    const outPath = join(ROOT, dir, '.lighthouserc.js');
    writeFileSync(
      outPath,
      readFileSync(join(SHARED_LIGHTHOUSE, '.lighthouserc.js'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
  }
}
