/**
 * Generates GitHub Actions workflows and dependabot.yml for templates.
 * Run via generate-configs.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { ROOT } from "./lib/utils.js";
import {
  TEMPLATE_DIRS,
  CODE_CHECK_SOURCE,
  TEST_SOURCE,
} from "./lib/stacks.js";

export function run(): void {
  const WORKFLOWS_DIR = join(ROOT, "shared", "workflows");
  const GEN_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/<name> instead.\n";

  // ── static-analysis.yml ────────────────────────────────────────────────────

  const STATIC_ANALYSIS_SRC = join(WORKFLOWS_DIR, "static-analysis.yml");
  const STATIC_ANALYSIS_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/static-analysis.yml instead.\n";
  const staticAnalysisContent = STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, "utf8");

  for (const dir of TEMPLATE_DIRS) {
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "static-analysis.yml");
    writeFileSync(outPath, staticAnalysisContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── code-check.yml ─────────────────────────────────────────────────────────

  for (const [dir, srcName] of Object.entries(CODE_CHECK_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "code-check.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── test.yml ───────────────────────────────────────────────────────────────

  for (const [dir, srcName] of Object.entries(TEST_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "test.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── dependabot.yml ─────────────────────────────────────────────────────────

  const DEPENDABOT_SRC = join(WORKFLOWS_DIR, "dependabot.yml");
  const dependabotContent =
    "# Generated by scripts/generate-configs.ts — edit shared/workflows/dependabot.yml instead.\n" +
    readFileSync(DEPENDABOT_SRC, "utf8");

  for (const dir of TEMPLATE_DIRS) {
    const outDir = join(ROOT, dir, ".github");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "dependabot.yml");
    writeFileSync(outPath, dependabotContent, "utf8");
    console.log("Generated:", outPath);
  }
}
