/**
 * Generates ESLint, Prettier, tsconfig, Vitest configs for templates.
 * Run via generate-configs.ts
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { pathToFileURL } from 'url';
import { TEMPLATES_DIR } from './lib/stacks.js';
import {
  ROOT,
  SHARED_CONFIG_STACKS,
  SHARED_ESLINT,
  SHARED_PRETTIER,
  SHARED_TSCONFIG,
  SHARED_VITEST,
} from './lib/utils.js';

const SHARED_MARKUPLINT = join(ROOT, 'shared', 'lint-format', 'markuplint');
const SHARED_LIGHTHOUSE = join(ROOT, 'shared', 'lighthouse');
const SHARED_KNIP = join(ROOT, 'shared', 'knip');
const SHARED_PLAYWRIGHT = join(ROOT, 'shared', 'playwright');
const SHARED_MOCKS = join(ROOT, 'shared', 'test', 'mocks');

export async function run(): Promise<void> {
  // ── ESLint ─────────────────────────────────────────────────────────────────

  const GEN_HEADER_ESLINT =
    '// Generated by scripts/generate-configs.ts — edit shared/lint-format/eslint/eslint.config.<stack>.js instead.\n\n';
  const td = TEMPLATES_DIR;
  const ESLINT_SOURCE: Array<{ dir: string; source: string }> = [
    { dir: `${td}/nodejs`, source: 'eslint.config.nodejs.js' },
    { dir: `${td}/reactjs`, source: 'eslint.config.react.js' },
    { dir: `${td}/nextjs`, source: 'eslint.config.nextjs.js' },
    { dir: `${td}/rails`, source: 'eslint.config.rails.js' },
    { dir: `${td}/rails-api`, source: 'eslint.config.rails.js' },
    { dir: 'full-templates/nextjs', source: 'eslint.config.nextjs-full.js' },
  ];
  for (const { dir, source } of ESLINT_SOURCE) {
    const stack = source.replace('eslint.config.', '').replace('.js', '');
    const content =
      GEN_HEADER_ESLINT.replace('<stack>', stack) +
      readFileSync(join(SHARED_ESLINT, source), 'utf8');
    writeFileSync(join(ROOT, dir, 'eslint.config.js'), content, 'utf8');
    console.log('Generated:', join(ROOT, dir, 'eslint.config.js'));
  }

  // ── Vitest ─────────────────────────────────────────────────────────────────

  const VITEST_HEADER =
    '// Generated by scripts/generate-configs.ts — edit shared/test/vitest/ instead.\n\n';
  const vitestNextjsEntries: Array<{
    dir: string;
    config: string;
    setup: string;
  }> = [
    {
      dir: `${td}/nextjs`,
      config: 'vitest.config.react-ts.minimal.ts',
      setup: 'vitest.setup.minimal.ts',
    },
    {
      dir: 'full-templates/nextjs',
      config: 'vitest.config.react-ts.ts',
      setup: 'vitest.setup.ts',
    },
  ];
  for (const {
    dir: vitestDir,
    config: configFile,
    setup: setupFile,
  } of vitestNextjsEntries) {
    writeFileSync(
      join(ROOT, vitestDir, 'vitest.config.ts'),
      VITEST_HEADER +
        readFileSync(join(SHARED_VITEST, configFile), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest.config.ts'));
    writeFileSync(
      join(ROOT, vitestDir, 'vitest.setup.ts'),
      VITEST_HEADER +
        readFileSync(join(SHARED_VITEST, setupFile), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest.setup.ts'));
    writeFileSync(
      join(ROOT, vitestDir, 'vitest-env.d.ts'),
      readFileSync(join(SHARED_VITEST, 'vitest-env.d.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', join(ROOT, vitestDir, 'vitest-env.d.ts'));
  }

  // ── Prettier（.ts ソースから .json を生成）─────────────────────────────────

  const prettierMod = await import(
    pathToFileURL(join(SHARED_PRETTIER, '.prettierrc.ts')).href
  );
  const prettierJson = JSON.stringify(prettierMod.default, null, 2);
  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, '.prettierrc.json');
    writeFileSync(outPath, prettierJson, 'utf8');
    console.log('Generated:', outPath);
  }

  // ── tsconfig（.ts ソースから .json を生成）─────────────────────────────────

  const reactRoot = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.root.ts')).href
  );
  const reactApp = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.app.ts')).href
  );
  const reactNode = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'reactjs', 'tsconfig.node.ts')).href
  );
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.json'),
    JSON.stringify(reactRoot.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.json'));
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.app.json'),
    JSON.stringify(reactApp.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.app.json'));
  writeFileSync(
    join(ROOT, td, 'reactjs', 'tsconfig.node.json'),
    JSON.stringify(reactNode.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'reactjs', 'tsconfig.node.json'));

  const nextjsTsMinimal = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'nextjs', 'tsconfig.minimal.ts')).href
  );
  const nextjsTsFull = await import(
    pathToFileURL(join(SHARED_TSCONFIG, 'nextjs', 'tsconfig.ts')).href
  );
  writeFileSync(
    join(ROOT, td, 'nextjs', 'tsconfig.json'),
    JSON.stringify(nextjsTsMinimal.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, td, 'nextjs', 'tsconfig.json'));
  writeFileSync(
    join(ROOT, 'full-templates/nextjs', 'tsconfig.json'),
    JSON.stringify(nextjsTsFull.default, null, 2),
    'utf8',
  );
  console.log('Generated:', join(ROOT, 'full-templates/nextjs', 'tsconfig.json'));

  // ── Markuplint (.markuplintrc.json) ────────────────────────────────────────

  const MARKUPLINT_REACT_DIRS = ['full-templates/nextjs'];
  for (const dir of MARKUPLINT_REACT_DIRS) {
    const outPath = join(ROOT, dir, '.markuplintrc.json');
    writeFileSync(
      outPath,
      readFileSync(join(SHARED_MARKUPLINT, '.markuplintrc.react.json'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
  }

  // ── Lighthouse CI (.lighthouserc.js) ──────────────────────────────────────

  const LIGHTHOUSE_DIRS = ['full-templates/nextjs'];
  for (const dir of LIGHTHOUSE_DIRS) {
    const outPath = join(ROOT, dir, '.lighthouserc.js');
    writeFileSync(
      outPath,
      readFileSync(join(SHARED_LIGHTHOUSE, '.lighthouserc.js'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
  }

  // ── Knip (knip.config.ts) ─────────────────────────────────────────────────

  const KNIP_HEADER =
    '// Generated by scripts/generate-configs.ts — edit shared/knip/ instead.\n\n';
  const KNIP_DIRS = ['full-templates/nextjs'];
  for (const dir of KNIP_DIRS) {
    const outPath = join(ROOT, dir, 'knip.config.ts');
    writeFileSync(
      outPath,
      KNIP_HEADER +
        readFileSync(join(SHARED_KNIP, 'knip.config.nextjs.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
  }

  // ── Playwright (playwright.config.ts) ──────────────────────────────────────

  const PLAYWRIGHT_HEADER =
    '// Generated by scripts/generate-configs.ts — edit shared/playwright/ instead.\n\n';
  const PLAYWRIGHT_SPECS_SOURCE = join(SHARED_PLAYWRIGHT, 'specs');
  const PLAYWRIGHT_DIRS = ['full-templates/nextjs'];
  for (const dir of PLAYWRIGHT_DIRS) {
    const outPath = join(ROOT, dir, 'playwright.config.ts');
    writeFileSync(
      outPath,
      PLAYWRIGHT_HEADER +
        readFileSync(join(SHARED_PLAYWRIGHT, 'playwright.config.nextjs.ts'), 'utf8'),
      'utf8',
    );
    console.log('Generated:', outPath);
    // tests/e2e/specs ディレクトリ作成とサンプル spec コピー
    const e2eDir = join(ROOT, dir, 'tests', 'e2e', 'specs');
    mkdirSync(e2eDir, { recursive: true });
    if (existsSync(PLAYWRIGHT_SPECS_SOURCE)) {
      const specFiles = readdirSync(PLAYWRIGHT_SPECS_SOURCE) as string[];
      for (const file of specFiles.filter((f: string) => f.endsWith('.spec.ts'))) {
        const content = readFileSync(join(PLAYWRIGHT_SPECS_SOURCE, file), 'utf8');
        writeFileSync(join(e2eDir, file), content, 'utf8');
        console.log('Generated:', join(dir, 'tests', 'e2e', 'specs', file));
      }
    }
  }

  // ── MSW mocks (src/mocks/) — full-templates のみ ───────────────────────────

  const MOCKS_DIRS = ['full-templates/nextjs'];
  for (const dir of MOCKS_DIRS) {
    const mocksOut = join(ROOT, dir, 'src', 'mocks');
    mkdirSync(mocksOut, { recursive: true });
    for (const file of ['handlers.ts', 'server.ts']) {
      const content = readFileSync(join(SHARED_MOCKS, file), 'utf8');
      const header =
        '// Generated by scripts/generate-configs.ts — edit shared/test/mocks/ instead.\n\n';
      writeFileSync(join(mocksOut, file), header + content, 'utf8');
      console.log('Generated:', join(dir, 'src', 'mocks', file));
    }
  }
}
