#!/usr/bin/env tsx
/**
 * Generates shared config files for all templates:
 *   - .prettierrc.json (from shared/prettier/)
 *   - .editorconfig (from shared/editorconfig/)
 *   - .github/workflows/static-analysis.yml
 * Run: yarn generate:configs
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT: string = process.cwd();

const SHARED_PRETTIER = join(ROOT, "shared", "prettier", ".prettierrc.json");
const SHARED_EDITORCONFIG = join(ROOT, "shared", "editorconfig", ".editorconfig");

// 横断的な共通設定を配るテンプレート一覧（Prettier / EditorConfig 対象）
const SHARED_CONFIG_STACKS: string[] = [
  "templates/nextjs",
  "templates/nodejs",
  "templates/react",
  "templates/rails",
  "templates/rails-api",
  "templates/ruby",
  "templates/sinatra",
];

// ── .prettierrc.json（shared からコピー）──────────────────────────────────────

const prettierContent = readFileSync(SHARED_PRETTIER, "utf8");
for (const dir of SHARED_CONFIG_STACKS) {
  const outPath = join(ROOT, dir, ".prettierrc.json");
  writeFileSync(outPath, prettierContent, "utf8");
  console.log("Generated:", outPath);
}

// ── .editorconfig（shared からコピー）──────────────────────────────────────────

const editorconfigContent = readFileSync(SHARED_EDITORCONFIG, "utf8");
for (const dir of SHARED_CONFIG_STACKS) {
  const outPath = join(ROOT, dir, ".editorconfig");
  writeFileSync(outPath, editorconfigContent, "utf8");
  console.log("Generated:", outPath);
}

// ── static-analysis.yml ───────────────────────────────────────────────────────

const STATIC_ANALYSIS_STACKS: string[] = ["templates/nextjs", "templates/nodejs", "templates/react", "templates/rails", "templates/rails-api", "templates/sinatra"];

const YAML_HEADER: string =
  "# Generated by scripts/generate-configs.ts — edit that file instead.\n";

const STATIC_ANALYSIS_YAML: string = `name: Static Analysis

on:
  pull_request:
    paths: '.github/workflows/*.yml'

defaults:
  run:
    shell: bash

concurrency:
  group: \${{ github.workflow }}-\${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
`;

for (const dir of STATIC_ANALYSIS_STACKS) {
  const outDir = join(ROOT, dir, ".github", "workflows");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "static-analysis.yml");
  writeFileSync(outPath, YAML_HEADER + STATIC_ANALYSIS_YAML, "utf8");
  console.log("Generated:", outPath);
}
