#!/usr/bin/env tsx
/**
 * Generates package.json, Gemfile, C# .csproj, global.json, .sln, and shared config into templates.
 *
 * - package.json: shared/npm/<stack>.json → templates/<stack>/package.json
 * - Gemfile:      shared/gemfile/Gemfile.<stack> → templates/<stack>/Gemfile
 * - .csproj:      shared/framework/dotnet/*.csproj → templates/csharp/
 * - global.json:  shared/framework/dotnet/global.json → templates/csharp/（SDK バージョンは shared/versions.json）
 * - .sln:         shared/framework/dotnet/TemplateCsharp.sln → templates/csharp/
 * - Go:           shared/lint-format/golangci/.golangci.yml → templates/go/.golangci.yml（設定のみ）
 * - Rust:         shared/rust-toolchain/rust-toolchain.toml → templates/rust/（設定のみ）
 *
 * Run: yarn generate:deps
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { NPM_STACKS, GEMFILE_STACKS } from "./lib/stacks.js";
import {
  ROOT,
  VERSIONS,
  SHARED_NPM,
  SHARED_GEMFILE,
  SHARED_DOTNET,
  SHARED_GOLANGCI,
  SHARED_RUST_TOOLCHAIN,
} from "./lib/utils.js";

const GEMFILE_HEADER =
  "# Generated by scripts/generate-deps.ts — edit shared/gemfile/ instead.\n\n";

const DOTNET_CSHARP_HEADER =
  "<!-- Generated by scripts/generate-deps.ts — edit shared/framework/dotnet/ instead. -->\n\n";

const SHARED_CONFIG_HEADER =
  "# Generated by scripts/generate-deps.ts — edit shared/ instead.\n\n";

/** shared/framework/dotnet/ の .csproj を templates/csharp/ にコピーする対応 */
const DOTNET_CSPROJ_MAP: { src: string; out: string }[] = [
  { src: "TemplateCsharp.csproj", out: "templates/csharp/TemplateCsharp.csproj" },
  {
    src: "TemplateCsharp.Tests.csproj",
    out: "templates/csharp/TemplateCsharp.Tests/TemplateCsharp.Tests.csproj",
  },
];

function run(): void {
  for (const stack of NPM_STACKS) {
    const srcPath = join(SHARED_NPM, `${stack}.json`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "package.json");
    writeFileSync(outPath, content + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  for (const stack of GEMFILE_STACKS) {
    const srcPath = join(SHARED_GEMFILE, `Gemfile.${stack}`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "Gemfile");
    writeFileSync(outPath, GEMFILE_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }

  for (const { src, out: outRel } of DOTNET_CSPROJ_MAP) {
    const srcPath = join(SHARED_DOTNET, src);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, outRel);
    writeFileSync(outPath, DOTNET_CSHARP_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }

  // C#: shared/framework/dotnet/global.json → templates/csharp/（SDK バージョンは versions.json の dotnet で上書き）
  const globalJsonSrc = readFileSync(join(SHARED_DOTNET, "global.json"), "utf8");
  const globalJson = JSON.parse(globalJsonSrc) as { sdk: { version: string; rollForward?: string } };
  if (VERSIONS.dotnet) globalJson.sdk.version = VERSIONS.dotnet;
  writeFileSync(join(ROOT, "templates/csharp/global.json"), JSON.stringify(globalJson, null, 2) + "\n", "utf8");
  console.log("Generated:", join(ROOT, "templates/csharp/global.json"));

  // C#: shared/framework/dotnet/TemplateCsharp.sln → templates/csharp/（.sln はコメント非対応のためヘッダなし）
  const slnContent = readFileSync(join(SHARED_DOTNET, "TemplateCsharp.sln"), "utf8");
  writeFileSync(join(ROOT, "templates/csharp/TemplateCsharp.sln"), slnContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/csharp/TemplateCsharp.sln"));

  // Go: shared/lint-format/golangci/ の設定のみ templates/go/ にコピー
  mkdirSync(join(ROOT, "templates/go"), { recursive: true });
  const golangciSrc = join(SHARED_GOLANGCI, ".golangci.yml");
  const golangciContent = readFileSync(golangciSrc, "utf8");
  writeFileSync(join(ROOT, "templates/go/.golangci.yml"), SHARED_CONFIG_HEADER + golangciContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/go/.golangci.yml"));

  // Rust: shared/rust-toolchain/ の設定のみ templates/rust/ にコピー
  mkdirSync(join(ROOT, "templates/rust"), { recursive: true });
  const rustToolchainSrc = join(SHARED_RUST_TOOLCHAIN, "rust-toolchain.toml");
  const rustToolchainContent = readFileSync(rustToolchainSrc, "utf8");
  writeFileSync(join(ROOT, "templates/rust/rust-toolchain.toml"), SHARED_CONFIG_HEADER + rustToolchainContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/rust/rust-toolchain.toml"));
}

run();
