#!/usr/bin/env node
/**
 * Generates shared config files for all templates:
 *   - .prettierrc.json
 *   - .github/workflows/static-analysis.yml
 * Run: yarn generate:configs
 */

import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();

// ── .prettierrc.json ──────────────────────────────────────────────────────────

const PRETTIER_STACKS = ["nextjs", "react", "rails", "rails-api", "ruby", "sinatra"];

const PRETTIER_CONFIG = {
  semi: true,
  singleQuote: true,
};

for (const dir of PRETTIER_STACKS) {
  const outPath = join(ROOT, dir, ".prettierrc.json");
  writeFileSync(outPath, JSON.stringify(PRETTIER_CONFIG, null, 2) + "\n", "utf8");
  console.log("Generated:", outPath);
}

// ── static-analysis.yml ───────────────────────────────────────────────────────

const STATIC_ANALYSIS_STACKS = ["nextjs", "react", "rails", "rails-api", "sinatra"];

const YAML_HEADER =
  "# Generated by scripts/generate-configs.js — edit that file instead.\n";

const STATIC_ANALYSIS_YAML = `name: Static Analysis

on:
  pull_request:
    paths: '.github/workflows/*.yml'

defaults:
  run:
    shell: bash

concurrency:
  group: \${{ github.workflow }}-\${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
`;

for (const dir of STATIC_ANALYSIS_STACKS) {
  const outDir = join(ROOT, dir, ".github", "workflows");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "static-analysis.yml");
  writeFileSync(outPath, YAML_HEADER + STATIC_ANALYSIS_YAML, "utf8");
  console.log("Generated:", outPath);
}
