#!/usr/bin/env tsx
/**
 * Generates shared config files for all templates:
 *   - .prettierrc.json (from shared/prettier/)
 *   - .editorconfig (from shared/editorconfig/)
 *   - .rspec (Ruby: languages/ruby/.rspec.common + 各 template の require)
 *   - templates/nodejs/eslint.config.mjs (from languages/node/eslint.config.base.mjs)
 *   - .rubocop.yml (Ruby: languages/ruby のベース + テンプレート用 fragment をマージ)
 *   - .github/workflows/static-analysis.yml
 * Run: yarn generate:configs
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import YAML from "yaml";

const ROOT: string = process.cwd();

function deepMerge<T extends Record<string, unknown>>(a: T, b: Record<string, unknown>): T {
  const r = { ...a } as Record<string, unknown>;
  for (const k of Object.keys(b)) {
    const av = r[k];
    const bv = b[k];
    if (bv != null && typeof bv === "object" && !Array.isArray(bv) && av != null && typeof av === "object" && !Array.isArray(av)) {
      r[k] = deepMerge(av as Record<string, unknown>, bv as Record<string, unknown>);
    } else {
      r[k] = bv;
    }
  }
  return r as T;
}

const SHARED_PRETTIER = join(ROOT, "shared", "prettier", ".prettierrc.json");
const SHARED_EDITORCONFIG = join(ROOT, "shared", "editorconfig", ".editorconfig");
const RSPEC_COMMON = join(ROOT, "languages", "ruby", ".rspec.common");
const NODE_ESLINT_BASE = join(ROOT, "languages", "node", "eslint.config.base.mjs");

// 横断的な共通設定を配るテンプレート一覧（Prettier / EditorConfig 対象）
const SHARED_CONFIG_STACKS: string[] = [
  "templates/nextjs",
  "templates/nodejs",
  "templates/react",
  "templates/rails",
  "templates/rails-api",
  "templates/ruby",
  "templates/sinatra",
];

// ── .prettierrc.json（shared からコピー）──────────────────────────────────────

const prettierContent = readFileSync(SHARED_PRETTIER, "utf8");
for (const dir of SHARED_CONFIG_STACKS) {
  const outPath = join(ROOT, dir, ".prettierrc.json");
  writeFileSync(outPath, prettierContent, "utf8");
  console.log("Generated:", outPath);
}

// ── .editorconfig（shared からコピー）──────────────────────────────────────────

const editorconfigContent = readFileSync(SHARED_EDITORCONFIG, "utf8");
for (const dir of SHARED_CONFIG_STACKS) {
  const outPath = join(ROOT, dir, ".editorconfig");
  writeFileSync(outPath, editorconfigContent, "utf8");
  console.log("Generated:", outPath);
}

// ── .rspec（languages/ruby の共通オプション + 各 template の --require）────────

const rspecCommonContent = readFileSync(RSPEC_COMMON, "utf8");
const RSPEC_REQUIRES: Record<string, string[]> = {
  "templates/rails": ["rails_helper"],
  "templates/rails-api": ["rails_helper", "swagger_helper"],
  "templates/sinatra": ["spec_helper"],
};
for (const [dir, requires] of Object.entries(RSPEC_REQUIRES)) {
  const requireLines = requires.map((r) => `--require ${r}`).join("\n");
  const content = requireLines + "\n" + rspecCommonContent;
  const outPath = join(ROOT, dir, ".rspec");
  writeFileSync(outPath, content, "utf8");
  console.log("Generated:", outPath);
}

// ── nodejs ESLint（languages/node からコピー）──────────────────────────────────

const nodeEslintContent = readFileSync(NODE_ESLINT_BASE, "utf8");
const nodejsEslintPath = join(ROOT, "templates", "nodejs", "eslint.config.mjs");
writeFileSync(nodejsEslintPath, nodeEslintContent, "utf8");
console.log("Generated:", nodejsEslintPath);

// ── .rubocop.yml（languages/ruby のベース + テンプレート用 fragment をマージ）────

const RUBY_LANG = join(ROOT, "languages", "ruby");
const rubocopBase = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop_base.yml"), "utf8")) as Record<string, unknown>;

const rubocopRails = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop.rails.yml"), "utf8")) as Record<string, unknown>;
const rubocopSinatra = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop.sinatra.yml"), "utf8")) as Record<string, unknown>;
const rubocopRailsApi = readFileSync(join(RUBY_LANG, ".rubocop.rails_api.yml"), "utf8");

const rubocopRailsMerged = deepMerge(rubocopBase, rubocopRails);
const rubocopSinatraMerged = deepMerge(rubocopBase, rubocopSinatra);

const RUBOCOP_OUT: Array<{ dir: string; content: string }> = [
  { dir: "templates/rails", content: YAML.stringify(rubocopRailsMerged) },
  { dir: "templates/sinatra", content: YAML.stringify(rubocopSinatraMerged) },
  { dir: "templates/ruby", content: YAML.stringify(rubocopBase) },
  { dir: "templates/rails-api", content: rubocopRailsApi },
];
for (const { dir, content } of RUBOCOP_OUT) {
  const outPath = join(ROOT, dir, ".rubocop.yml");
  writeFileSync(outPath, content, "utf8");
  console.log("Generated:", outPath);
}

// ── static-analysis.yml（shared からコピー）────────────────────────────────────

const STATIC_ANALYSIS_STACKS: string[] = ["templates/nextjs", "templates/nodejs", "templates/react", "templates/rails", "templates/rails-api", "templates/sinatra"];
const STATIC_ANALYSIS_SRC = join(ROOT, "shared", "workflows", "static-analysis.yml");
const STATIC_ANALYSIS_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/static-analysis.yml instead.\n";
const staticAnalysisContent = STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, "utf8");

for (const dir of STATIC_ANALYSIS_STACKS) {
  const outDir = join(ROOT, dir, ".github", "workflows");
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, "static-analysis.yml");
  writeFileSync(outPath, staticAnalysisContent, "utf8");
  console.log("Generated:", outPath);
}
