#!/usr/bin/env tsx
/**
 * Generates shared config files for all templates.
 * 方針: まず .ts で生成し、ツールが求める場合のみ .json を生成する。
 *
 * .ts で出力: eslint.config.ts, vitest.config.ts 等
 * .ts ソースから .json を生成: .prettierrc.json（shared/prettier/.prettierrc.ts）, tsconfig（shared/tsconfig/ 内の .ts）
 *
 * Run: yarn generate:configs
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { pathToFileURL } from "url";
import YAML from "yaml";
import { TEMPLATE_README_CONFIGS, getGeneratedReadmeContent } from "./template-readme-config.js";

const ROOT: string = process.cwd();

function deepMerge<T extends Record<string, unknown>>(a: T, b: Record<string, unknown>): T {
  const r = { ...a } as Record<string, unknown>;
  for (const k of Object.keys(b)) {
    const av = r[k];
    const bv = b[k];
    if (bv != null && typeof bv === "object" && !Array.isArray(bv) && av != null && typeof av === "object" && !Array.isArray(av)) {
      r[k] = deepMerge(av as Record<string, unknown>, bv as Record<string, unknown>);
    } else {
      r[k] = bv;
    }
  }
  return r as T;
}

const SHARED_EDITORCONFIG = join(ROOT, "shared", "editorconfig", ".editorconfig");
const GITIGNORE_DIR = join(ROOT, "shared", "gitignore");
const RSPEC_COMMON = join(ROOT, "languages", "ruby", ".rspec.common");
const NODE_LANG = join(ROOT, "languages", "node");
const SHARED_TSCONFIG = join(ROOT, "shared", "tsconfig");
const SHARED_VITEST = join(ROOT, "shared", "vitest");

// 横断的な共通設定を配るテンプレート一覧（Prettier / EditorConfig 対象）
const SHARED_CONFIG_STACKS: string[] = [
  "templates/nextjs",
  "templates/nodejs",
  "templates/react",
  "templates/rails",
  "templates/rails-api",
  "templates/ruby",
  "templates/sinatra",
];

async function run(): Promise<void> {
  // ── .editorconfig（shared からコピー）──────────────────────────────────────────

const editorconfigContent = readFileSync(SHARED_EDITORCONFIG, "utf8");
for (const dir of SHARED_CONFIG_STACKS) {
  const outPath = join(ROOT, dir, ".editorconfig");
  writeFileSync(outPath, editorconfigContent, "utf8");
  console.log("Generated:", outPath);
  }

  // ── .gitignore（shared/gitignore からスタック別にコピー）────────────────────────

  const GITIGNORE_SOURCE: Record<string, string> = {
    "templates/nextjs": ".gitignore.node",
    "templates/nodejs": ".gitignore.node",
    "templates/react": ".gitignore.node",
    "templates/rails": ".gitignore.rails",
    "templates/rails-api": ".gitignore.rails",
    "templates/ruby": ".gitignore.ruby",
    "templates/sinatra": ".gitignore.ruby",
  };

  const GITIGNORE_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/gitignore/ instead.\n\n";
  for (const [dir, srcName] of Object.entries(GITIGNORE_SOURCE)) {
    const srcPath = join(GITIGNORE_DIR, srcName);
    const content = GITIGNORE_HEADER + readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, dir, ".gitignore");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .rspec（languages/ruby の共通オプション + 各 template の --require）────────

  const rspecCommonContent = readFileSync(RSPEC_COMMON, "utf8");
  const RSPEC_REQUIRES: Record<string, string[]> = {
    "templates/rails": ["rails_helper"],
    "templates/rails-api": ["rails_helper", "swagger_helper"],
    "templates/sinatra": ["spec_helper"],
  };
  for (const [dir, requires] of Object.entries(RSPEC_REQUIRES)) {
    const requireLines = requires.map((r) => `--require ${r}`).join("\n");
    const content = requireLines + "\n" + rspecCommonContent;
    const outPath = join(ROOT, dir, ".rspec");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── まず .ts で出力: ESLint, Vitest ────────────────────────────────────────────

  const GEN_HEADER_ESLINT = "// Generated by scripts/generate-configs.ts — edit languages/node/eslint.config.<stack>.ts instead.\n\n";
  const nodeEslintContent = readFileSync(join(NODE_LANG, "eslint.config.base.ts"), "utf8");
  writeFileSync(join(ROOT, "templates/nodejs", "eslint.config.ts"), GEN_HEADER_ESLINT.replace("<stack>", "base") + nodeEslintContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/nodejs", "eslint.config.ts"));

  const ESLINT_SOURCE: Array<{ dir: string; source: string }> = [
    { dir: "templates/react", source: "eslint.config.react.ts" },
    { dir: "templates/nextjs", source: "eslint.config.nextjs.ts" },
    { dir: "templates/rails", source: "eslint.config.rails.ts" },
  ];
  for (const { dir, source } of ESLINT_SOURCE) {
    const stack = source.replace("eslint.config.", "").replace(".ts", "");
    const content = GEN_HEADER_ESLINT.replace("<stack>", stack) + readFileSync(join(NODE_LANG, source), "utf8");
    writeFileSync(join(ROOT, dir, "eslint.config.ts"), content, "utf8");
    console.log("Generated:", join(ROOT, dir, "eslint.config.ts"));
  }

  // ── Vitest（Next: shared/vitest から .ts で生成）────────────────────────────────────

  const VITEST_HEADER = "// Generated by scripts/generate-configs.ts — edit shared/vitest/ instead.\n\n";
  const vitestConfigContent = VITEST_HEADER + readFileSync(join(SHARED_VITEST, "vitest.config.vite-react.ts"), "utf8");
  writeFileSync(join(ROOT, "templates/nextjs", "vitest.config.ts"), vitestConfigContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/nextjs", "vitest.config.ts"));
  writeFileSync(join(ROOT, "templates/nextjs", "vitest.setup.ts"), VITEST_HEADER + readFileSync(join(SHARED_VITEST, "vitest.setup.ts"), "utf8"), "utf8");
  console.log("Generated:", join(ROOT, "templates/nextjs", "vitest.setup.ts"));
  writeFileSync(join(ROOT, "templates/nextjs", "vitest-env.d.ts"), readFileSync(join(SHARED_VITEST, "vitest-env.d.ts"), "utf8"), "utf8");
  console.log("Generated:", join(ROOT, "templates/nextjs", "vitest-env.d.ts"));

  // ── .rubocop.yml（languages/ruby のベース + テンプレート用 fragment をマージ）────

  const RUBY_LANG = join(ROOT, "languages", "ruby");
  const rubocopBase = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop_base.yml"), "utf8")) as Record<string, unknown>;

  const rubocopRails = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop.rails.yml"), "utf8")) as Record<string, unknown>;
  const rubocopSinatra = YAML.parse(readFileSync(join(RUBY_LANG, ".rubocop.sinatra.yml"), "utf8")) as Record<string, unknown>;
  const rubocopRailsApi = readFileSync(join(RUBY_LANG, ".rubocop.rails_api.yml"), "utf8");

  const rubocopRailsMerged = deepMerge(rubocopBase, rubocopRails);
  const rubocopSinatraMerged = deepMerge(rubocopBase, rubocopSinatra);

  const RUBOCOP_OUT: Array<{ dir: string; content: string }> = [
    { dir: "templates/rails", content: YAML.stringify(rubocopRailsMerged) },
    { dir: "templates/sinatra", content: YAML.stringify(rubocopSinatraMerged) },
    { dir: "templates/ruby", content: YAML.stringify(rubocopBase) },
    { dir: "templates/rails-api", content: rubocopRailsApi },
  ];
  for (const { dir, content } of RUBOCOP_OUT) {
    const outPath = join(ROOT, dir, ".rubocop.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── 次に .ts ソースから .json を生成: Prettier, tsconfig ────────────────────────

  const prettierMod = await import(pathToFileURL(join(ROOT, "shared", "prettier", ".prettierrc.ts")).href);
  const prettierJson = JSON.stringify(prettierMod.default, null, 2);
  for (const dir of SHARED_CONFIG_STACKS) {
    const outPath = join(ROOT, dir, ".prettierrc.json");
    writeFileSync(outPath, prettierJson, "utf8");
    console.log("Generated:", outPath);
  }

  // tsconfig: .ts を import して .json を出力（JSON のみなのでコメントは付けない）
  const reactRoot = await import(pathToFileURL(join(SHARED_TSCONFIG, "react", "tsconfig.root.ts")).href);
  const reactApp = await import(pathToFileURL(join(SHARED_TSCONFIG, "react", "tsconfig.app.ts")).href);
  const reactNode = await import(pathToFileURL(join(SHARED_TSCONFIG, "react", "tsconfig.node.ts")).href);
  writeFileSync(join(ROOT, "templates/react", "tsconfig.json"), JSON.stringify(reactRoot.default, null, 2), "utf8");
  console.log("Generated:", join(ROOT, "templates/react", "tsconfig.json"));
  writeFileSync(join(ROOT, "templates/react", "tsconfig.app.json"), JSON.stringify(reactApp.default, null, 2), "utf8");
  console.log("Generated:", join(ROOT, "templates/react", "tsconfig.app.json"));
  writeFileSync(join(ROOT, "templates/react", "tsconfig.node.json"), JSON.stringify(reactNode.default, null, 2), "utf8");
  console.log("Generated:", join(ROOT, "templates/react", "tsconfig.node.json"));

  const nextjsTs = await import(pathToFileURL(join(SHARED_TSCONFIG, "nextjs", "tsconfig.ts")).href);
  writeFileSync(join(ROOT, "templates/nextjs", "tsconfig.json"), JSON.stringify(nextjsTs.default, null, 2), "utf8");
  console.log("Generated:", join(ROOT, "templates/nextjs", "tsconfig.json"));

  const railsTs = await import(pathToFileURL(join(SHARED_TSCONFIG, "rails", "tsconfig.ts")).href);
  writeFileSync(join(ROOT, "templates/rails", "tsconfig.json"), JSON.stringify(railsTs.default, null, 2), "utf8");
  console.log("Generated:", join(ROOT, "templates/rails", "tsconfig.json"));

  // ── static-analysis.yml（shared からコピー）────────────────────────────────────

  const STATIC_ANALYSIS_STACKS: string[] = ["templates/nextjs", "templates/nodejs", "templates/react", "templates/rails", "templates/rails-api", "templates/sinatra"];
  const STATIC_ANALYSIS_SRC = join(ROOT, "shared", "workflows", "static-analysis.yml");
  const STATIC_ANALYSIS_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/static-analysis.yml instead.\n";
  const staticAnalysisContent = STATIC_ANALYSIS_HEADER + readFileSync(STATIC_ANALYSIS_SRC, "utf8");

  for (const dir of STATIC_ANALYSIS_STACKS) {
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "static-analysis.yml");
    writeFileSync(outPath, staticAnalysisContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── code-check.yml / test.yml / dependabot.yml ────────────────────────────────────

  const WORKFLOWS_DIR = join(ROOT, "shared", "workflows");
  const GEN_HEADER = "# Generated by scripts/generate-configs.ts — edit shared/workflows/<name> instead.\n";

  const CODE_CHECK_SOURCE: Record<string, string> = {
    "templates/nextjs": "code-check-node.yml",
    "templates/nodejs": "code-check-node.yml",
    "templates/react": "code-check-node.yml",
    "templates/rails-api": "code-check-ruby.yml",
    "templates/sinatra": "code-check-ruby-erb.yml",
    "templates/rails": "code-check-ruby-erb.yml",
  };

  for (const [dir, srcName] of Object.entries(CODE_CHECK_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "code-check.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  const TEST_SOURCE: Record<string, string> = {
    "templates/react": "test-node.yml",
    "templates/sinatra": "test-sinatra.yml",
    "templates/rails": "test-rails.yml",
    "templates/rails-api": "test-rails-api.yml",
  };

  for (const [dir, srcName] of Object.entries(TEST_SOURCE)) {
    const srcPath = join(WORKFLOWS_DIR, srcName);
    const content = GEN_HEADER.replace("<name>", srcName) + readFileSync(srcPath, "utf8");
    const outDir = join(ROOT, dir, ".github", "workflows");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "test.yml");
    writeFileSync(outPath, content, "utf8");
    console.log("Generated:", outPath);
  }

  // ── .env.example / .env.test / .env.development ──────────────────────────────────

  const SHARED_ENV = join(ROOT, "shared", "env");
  const DB_ENV_PATH = join(SHARED_ENV, "db.env");
  const ENV_TEMPLATES: Array<{ dir: string; variant: "rails" | "sinatra"; templateId: string }> = [
    { dir: "templates/rails-api", variant: "rails", templateId: "template-rails-api" },
    { dir: "templates/sinatra", variant: "sinatra", templateId: "template-sinatra" },
  ];

  const dbEnvContent = readFileSync(DB_ENV_PATH, "utf8");

  type EnvKind = "example" | "test" | "development";
  const ENV_KINDS: Array<{ kind: EnvKind; envValue: string; suffix: string }> = [
    { kind: "example", envValue: "development", suffix: "_development" },
    { kind: "test", envValue: "test", suffix: "_test" },
    { kind: "development", envValue: "development", suffix: "_development" },
  ];

  for (const { dir, variant, templateId } of ENV_TEMPLATES) {
    const headPath = join(SHARED_ENV, `${variant}.env.head`);
    const headTemplate = readFileSync(headPath, "utf8");

    for (const { kind, envValue, suffix } of ENV_KINDS) {
      const head = headTemplate.replace(/\{\{ENV\}\}/g, envValue);
      const db = dbEnvContent
        .replace(/\{\{TEMPLATE_ID\}\}/g, templateId)
        .replace(/\{\{SUFFIX\}\}/g, suffix);
      const content = head + db;
      const outPath = join(ROOT, dir, `.env.${kind}`);
      writeFileSync(outPath, content, "utf8");
      console.log("Generated:", outPath);
    }
  }

  // ── dependabot.yml ─────────────────────────────────────────────────────────────

  const DEPENDABOT_SRC = join(ROOT, "shared", "workflows", "dependabot.yml");
  const dependabotContent =
    "# Generated by scripts/generate-configs.ts — edit shared/workflows/dependabot.yml instead.\n" +
    readFileSync(DEPENDABOT_SRC, "utf8");

  for (const dir of STATIC_ANALYSIS_STACKS) {
    const outDir = join(ROOT, dir, ".github");
    mkdirSync(outDir, { recursive: true });
    const outPath = join(outDir, "dependabot.yml");
    writeFileSync(outPath, dependabotContent, "utf8");
    console.log("Generated:", outPath);
  }

  // ── templates/<id>/README.md ─────────────────────────────────────────────────────

  for (const config of TEMPLATE_README_CONFIGS) {
    const outPath = join(ROOT, "templates", config.id, "README.md");
    writeFileSync(outPath, getGeneratedReadmeContent(config), "utf8");
    console.log("Generated:", outPath);
  }
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
