#!/usr/bin/env tsx
/**
 * Generates package.json, Gemfile, and C# .csproj for each template from shared definitions.
 *
 * - package.json: shared/npm/<stack>.json → templates/<stack>/package.json
 * - Gemfile:      shared/gemfile/Gemfile.<stack> → templates/<stack>/Gemfile
 * - .csproj:      shared/dotnet/*.csproj → templates/csharp/
 *
 * Run: yarn generate:deps
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();
const SHARED_NPM = join(ROOT, "shared", "npm");
const SHARED_GEMFILE = join(ROOT, "shared", "gemfile");
const SHARED_DOTNET = join(ROOT, "shared", "dotnet");

const NPM_STACKS = ["nextjs", "nodejs", "reactjs", "rails", "rails-api", "sinatra", "ruby"] as const;
const GEMFILE_STACKS = ["rails", "rails-api", "sinatra", "ruby"] as const;

const GEMFILE_HEADER =
  "# Generated by scripts/generate-deps.ts — edit shared/gemfile/ instead.\n\n";

const DOTNET_CSHARP_HEADER =
  "<!-- Generated by scripts/generate-deps.ts — edit shared/dotnet/ instead. -->\n\n";

/** shared/dotnet/ の .csproj を templates/csharp/ にコピーする対応 */
const DOTNET_CSPROJ_MAP: { src: string; out: string }[] = [
  { src: "TemplateCsharp.csproj", out: "templates/csharp/TemplateCsharp.csproj" },
  {
    src: "TemplateCsharp.Tests.csproj",
    out: "templates/csharp/TemplateCsharp.Tests/TemplateCsharp.Tests.csproj",
  },
];

function run(): void {
  for (const stack of NPM_STACKS) {
    const srcPath = join(SHARED_NPM, `${stack}.json`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "package.json");
    writeFileSync(outPath, content + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  for (const stack of GEMFILE_STACKS) {
    const srcPath = join(SHARED_GEMFILE, `Gemfile.${stack}`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "Gemfile");
    writeFileSync(outPath, GEMFILE_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }

  for (const { src, out: outRel } of DOTNET_CSPROJ_MAP) {
    const srcPath = join(SHARED_DOTNET, src);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, outRel);
    writeFileSync(outPath, DOTNET_CSHARP_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }
}

run();
