#!/usr/bin/env tsx
/**
 * Generates package.json, Gemfile, C# .csproj, and shared config into templates.
 *
 * - package.json: shared/npm/<stack>.json → templates/<stack>/package.json
 * - Gemfile:      shared/gemfile/Gemfile.<stack> → templates/<stack>/Gemfile
 * - .csproj:      shared/dotnet/*.csproj → templates/csharp/
 * - Go:           shared/golangci/.golangci.yml → templates/go/.golangci.yml（設定のみ）
 * - Rust:         shared/rust-toolchain/rust-toolchain.toml → templates/rust/（設定のみ）
 *
 * Run: yarn generate:deps
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();
const SHARED_NPM = join(ROOT, "shared", "npm");
const SHARED_GEMFILE = join(ROOT, "shared", "gemfile");
const SHARED_DOTNET = join(ROOT, "shared", "dotnet");
const SHARED_GOLANGCI = join(ROOT, "shared", "golangci");
const SHARED_RUST_TOOLCHAIN = join(ROOT, "shared", "rust-toolchain");

const NPM_STACKS = ["nextjs", "nodejs", "reactjs", "rails", "rails-api", "sinatra"] as const;
const GEMFILE_STACKS = ["rails", "rails-api", "sinatra"] as const;

const GEMFILE_HEADER =
  "# Generated by scripts/generate-deps.ts — edit shared/gemfile/ instead.\n\n";

const DOTNET_CSHARP_HEADER =
  "<!-- Generated by scripts/generate-deps.ts — edit shared/dotnet/ instead. -->\n\n";

const SHARED_CONFIG_HEADER =
  "# Generated by scripts/generate-deps.ts — edit shared/ instead.\n\n";

/** shared/dotnet/ の .csproj を templates/csharp/ にコピーする対応 */
const DOTNET_CSPROJ_MAP: { src: string; out: string }[] = [
  { src: "TemplateCsharp.csproj", out: "templates/csharp/TemplateCsharp.csproj" },
  {
    src: "TemplateCsharp.Tests.csproj",
    out: "templates/csharp/TemplateCsharp.Tests/TemplateCsharp.Tests.csproj",
  },
];

function run(): void {
  for (const stack of NPM_STACKS) {
    const srcPath = join(SHARED_NPM, `${stack}.json`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "package.json");
    writeFileSync(outPath, content + "\n", "utf8");
    console.log("Generated:", outPath);
  }

  for (const stack of GEMFILE_STACKS) {
    const srcPath = join(SHARED_GEMFILE, `Gemfile.${stack}`);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, "templates", stack, "Gemfile");
    writeFileSync(outPath, GEMFILE_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }

  for (const { src, out: outRel } of DOTNET_CSPROJ_MAP) {
    const srcPath = join(SHARED_DOTNET, src);
    const content = readFileSync(srcPath, "utf8");
    const outPath = join(ROOT, outRel);
    writeFileSync(outPath, DOTNET_CSHARP_HEADER + content, "utf8");
    console.log("Generated:", outPath);
  }

  // Go: shared/golangci/ の設定のみ templates/go/ にコピー
  mkdirSync(join(ROOT, "templates/go"), { recursive: true });
  const golangciSrc = join(SHARED_GOLANGCI, ".golangci.yml");
  const golangciContent = readFileSync(golangciSrc, "utf8");
  writeFileSync(join(ROOT, "templates/go/.golangci.yml"), SHARED_CONFIG_HEADER + golangciContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/go/.golangci.yml"));

  // Rust: shared/rust-toolchain/ の設定のみ templates/rust/ にコピー
  mkdirSync(join(ROOT, "templates/rust"), { recursive: true });
  const rustToolchainSrc = join(SHARED_RUST_TOOLCHAIN, "rust-toolchain.toml");
  const rustToolchainContent = readFileSync(rustToolchainSrc, "utf8");
  writeFileSync(join(ROOT, "templates/rust/rust-toolchain.toml"), SHARED_CONFIG_HEADER + rustToolchainContent, "utf8");
  console.log("Generated:", join(ROOT, "templates/rust/rust-toolchain.toml"));
}

run();
