// Generated by scripts/generate-configs.ts — edit shared/framework/nextjs/next.config.ts instead.

import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  output: 'export',
  trailingSlash: true,
};

export default nextConfig;
