require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'coverage/**/*'
    - 'spec/support/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/factories/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

inherit_mode:
  merge:
    - Exclude

# Rails cops
Rails:
  Enabled: true

# RSpec cops
RSpec:
  Enabled: true

Style/Documentation:
  Enabled: false
